/**
 * Shader codegen for the radiance cascades library. The WGSL lives as
 * standalone files in `lib/radiance-cascades/shaders/`; this expands their
 * `// #include "file.wgsl"` lines, validates every complete program with
 * `naga` (no TypeScript, no GPU, milliseconds), and writes the embedded
 * strings the browser imports to `lib/radiance-cascades/wgsl.generated.ts`.
 *
 *   deno run -A --no-lock tools/gen_shaders.ts          # regenerate (fails on invalid WGSL)
 *   deno run -A --no-lock tools/gen_shaders.ts --check  # also fail if the output is stale
 *
 * A file without an entry point (`@vertex`/`@fragment`) is include-only and
 * is validated through the programs that include it.
 */

// The project sits outside the deno workspace, so no import map applies.
// deno-lint-ignore no-import-prefix
import { basename, dirname, fromFileUrl, join } from "jsr:@std/path@1";

const HERE = dirname(fromFileUrl(import.meta.url));
const SHADER_DIR = join(HERE, "../lib/radiance-cascades/shaders");
const OUTPUT = join(HERE, "../lib/radiance-cascades/wgsl.generated.ts");
const INCLUDE = /^\s*\/\/\s*#include\s+"([^"]+)"\s*$/;

const sources = new Map<string, string>();
for await (const entry of Deno.readDir(SHADER_DIR)) {
  if (entry.isFile && entry.name.endsWith(".wgsl")) {
    sources.set(
      entry.name,
      await Deno.readTextFile(join(SHADER_DIR, entry.name)),
    );
  }
}

function expand(name: string, stack: string[] = []): string {
  const source = sources.get(name);
  if (source === undefined) {
    throw new Error(`${stack.at(-1) ?? "?"}: no shader file "${name}"`);
  }
  if (stack.includes(name)) {
    throw new Error(`include cycle: ${[...stack, name].join(" -> ")}`);
  }
  return source.split("\n").map((line) => {
    const match = INCLUDE.exec(line);
    return match
      ? `// ---- ${match[1]} ----\n${expand(match[1], [...stack, name])}`
      : line;
  }).join("\n");
}

async function validate(name: string, code: string): Promise<string[]> {
  const command = new Deno.Command("naga", {
    args: ["--stdin-file-path", name],
    stdin: "piped",
    stdout: "piped",
    stderr: "piped",
  });
  const child = command.spawn();
  const writer = child.stdin.getWriter();
  await writer.write(new TextEncoder().encode(code));
  await writer.close();
  const result = await child.output();
  if (result.success) return [];
  const text = new TextDecoder().decode(result.stderr) +
    new TextDecoder().decode(result.stdout);
  return [text.trim()];
}

const isProgram = (code: string) => /@(vertex|fragment|compute)\b/.test(code);
const exportName = (file: string) =>
  `${basename(file, ".wgsl").toUpperCase()}_WGSL`;

let failed = false;
const chunks: string[] = [
  "// Generated by tools/gen_shaders.ts from lib/radiance-cascades/shaders/*.wgsl.",
  "// DO NOT EDIT; edit the .wgsl files and regenerate.",
  "",
];
for (const name of [...sources.keys()].sort()) {
  const code = expand(name);
  if (!isProgram(code)) continue;
  const errors = await validate(name, code);
  if (errors.length > 0) {
    failed = true;
    console.error(`✗ ${name}\n${errors.join("\n")}\n`);
    continue;
  }
  console.log(`✓ ${name}`);
  const escaped = code.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(
    /\$\{/g,
    "\\${",
  );
  chunks.push(`/** ${name}, includes expanded. */`);
  // Match `deno fmt`: the template moves to its own line only when the
  // declaration's first line would exceed 80 columns.
  const head = `export const ${exportName(name)} = \``;
  const firstLine = escaped.split("\n")[0];
  chunks.push(
    head.length + firstLine.length > 80
      ? `export const ${exportName(name)} =\n  \`${escaped}\`;`
      : `${head}${escaped}\`;`,
  );
  chunks.push("");
}
if (failed) {
  console.error("naga rejected a shader; wgsl.generated.ts left untouched");
  Deno.exit(1);
}
const output = chunks.join("\n");
const previous = await Deno.readTextFile(OUTPUT).catch(() => null);
if (Deno.args.includes("--check")) {
  if (previous !== output) {
    console.error(`${OUTPUT} is stale; run tools/gen_shaders.ts`);
    Deno.exit(1);
  }
  console.log("wgsl.generated.ts is up to date");
} else if (previous !== output) {
  await Deno.writeTextFile(OUTPUT, output);
  console.log(`wrote ${OUTPUT}`);
} else {
  console.log("wgsl.generated.ts unchanged");
}
