// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
import {
  CustomShaderEffect,
  type Dynamic,
  type MaterialHandles,
  type ShaderSource,
  type ShaderUniforms,
  type UniformDescriptor,
} from "@avtools/shader-fx/raw";
export const AlphaScaleVertexSource =
  `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct VertexOutput {
  @builtin(position) position: vec4f,
  @location(0) vUV: vec2f,
};

@vertex
fn main(@builtin(vertex_index) index: u32) -> VertexOutput {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  var uvs = array<vec2f, 3>(
    vec2f(0.0, 1.0),
    vec2f(2.0, 1.0),
    vec2f(0.0, -1.0),
  );
  var out: VertexOutput;
  out.position = vec4f(positions[index], 0.0, 1.0);
  out.vUV = uvs[index];
  return out;
}

`;
export const AlphaScaleFragmentSources = [
  `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct AlphaScaleUniforms {
  opacity: f32, // 1.0
};

fn pass0(
  uv: vec2f,
  uniforms: AlphaScaleUniforms,
  src: texture_2d<f32>,
  srcSampler: sampler,
) -> vec4f {
  let color = textureSample(src, srcSampler, uv);
  return vec4f(color.rgb, color.a * uniforms.opacity);
}

@group(0) @binding(0) var<uniform> uniforms: AlphaScaleUniforms;
@group(0) @binding(1) var src: texture_2d<f32>;
@group(0) @binding(2) var srcSampler: sampler;

struct FragmentInput {
  @location(0) vUV: vec2f,
};

@fragment
fn main(input: FragmentInput) -> @location(0) vec4f {
  let uv_local = input.vUV;
  let uniforms_value = uniforms;
  let color = pass0(uv_local, uniforms_value, src, srcSampler);
  return color;
}

`, // pass0
] as const;
export const AlphaScalePassCount = 1 as const;
export const AlphaScalePrimaryTextureName = "src" as const;

export const AlphaScalePassTextureSources = [
  [
    { binding: "src", source: { kind: "input", key: "src" } },
  ],
] as const;

export const AlphaScaleUniformMeta: UniformDescriptor[] = [
  {
    name: "opacity",
    kind: "f32",
    bindingName: "uniforms_opacity",
    default: 1.0,
  },
];

export interface AlphaScaleUniforms {
  opacity: number;
}

export const AlphaScaleUniformsDefaults: AlphaScaleUniforms = {
  opacity: 0,
};

const AlphaScaleUniformsLayoutSize = 4;

function packAlphaScaleUniforms(
  floatView: Float32Array,
  intView: Int32Array,
  uintView: Uint32Array,
  floatOffset: number,
  value: AlphaScaleUniforms,
): void {
  {
    const base = floatOffset + 0;
    const raw = value.opacity;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
}

export type AlphaScaleTextureName = "src";
export const AlphaScaleTextureNames = ["src"] as const;
export interface AlphaScaleInputs {
  src: ShaderSource;
}

export type AlphaScaleMaterialHandles = MaterialHandles<
  AlphaScaleUniforms,
  AlphaScaleTextureName
>;

export interface AlphaScaleMaterialOptions {
  name?: string;
  passIndex?: number;
  sampleMode?: "nearest" | "linear";
}

export function createAlphaScaleMaterial(
  device: GPUDevice,
  format: GPUTextureFormat,
  options: AlphaScaleMaterialOptions = {},
): AlphaScaleMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(
      `Invalid passIndex ${passIndex} for AlphaScale. Expected 0 <= passIndex < 1.`,
    );
  }
  const uniformData = new ArrayBuffer(AlphaScaleUniformsLayoutSize);
  const uniformFloats = new Float32Array(uniformData);
  const uniformInts = new Int32Array(uniformData);
  const uniformUints = new Uint32Array(uniformData);
  let currentUniforms: AlphaScaleUniforms = { ...AlphaScaleUniformsDefaults };
  packAlphaScaleUniforms(
    uniformFloats,
    uniformInts,
    uniformUints,
    0,
    currentUniforms,
  );
  const uniformBuffer = device.createBuffer({
    size: uniformData.byteLength,
    usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST,
  });
  device.queue.writeBuffer(uniformBuffer, 0, uniformData);

  const bindGroupLayout = device.createBindGroupLayout({
    entries: [
      {
        binding: 0,
        visibility: GPUShaderStage.FRAGMENT,
        buffer: { type: "uniform" },
      },
      {
        binding: 1,
        visibility: GPUShaderStage.FRAGMENT,
        texture: { sampleType: "float" },
      },
      {
        binding: 2,
        visibility: GPUShaderStage.FRAGMENT,
        sampler: { type: "filtering" },
      },
    ],
  });

  const pipelineLayout = device.createPipelineLayout({
    bindGroupLayouts: [bindGroupLayout],
  });
  const vertexModule = device.createShaderModule({
    code: AlphaScaleVertexSource,
  });
  const fragmentModule = device.createShaderModule({
    code: AlphaScaleFragmentSources[passIndex],
  });

  const pipeline = device.createRenderPipeline({
    layout: pipelineLayout,
    vertex: { module: vertexModule, entryPoint: "main" },
    fragment: {
      module: fragmentModule,
      entryPoint: "main",
      targets: [{ format }],
    },
    primitive: { topology: "triangle-list", cullMode: "none" },
  });

  const samplers: Record<string, GPUSampler> = {};
  const textureViews: Record<string, GPUTextureView> = {};
  for (const name of AlphaScaleTextureNames) {
    const filter = options.sampleMode ?? "linear";
    samplers[name] = device.createSampler({
      magFilter: filter,
      minFilter: filter,
    });
    const placeholder = device.createTexture({
      size: { width: 1, height: 1 },
      format,
      usage: GPUTextureUsage.TEXTURE_BINDING,
    });
    textureViews[name] = placeholder.createView();
  }

  let bindGroup = device.createBindGroup({
    layout: bindGroupLayout,
    entries: [
      { binding: 0, resource: { buffer: uniformBuffer } },
      { binding: 1, resource: textureViews["src"] },
      { binding: 2, resource: samplers["src"] },
    ],
  });

  const rebuildBindGroup = () => {
    bindGroup = device.createBindGroup({
      layout: bindGroupLayout,
      entries: [
        { binding: 0, resource: { buffer: uniformBuffer } },
        { binding: 1, resource: textureViews["src"] },
        { binding: 2, resource: samplers["src"] },
      ],
    });
  };

  const handles: AlphaScaleMaterialHandles = {
    pipeline,
    get bindGroup() {
      return bindGroup;
    },
    setTexture: (name, texture) => {
      textureViews[name] = texture;
      rebuildBindGroup();
    },
    setUniforms: (updates) => {
      currentUniforms = { ...currentUniforms, ...updates };
      packAlphaScaleUniforms(
        uniformFloats,
        uniformInts,
        uniformUints,
        0,
        currentUniforms,
      );
      device.queue.writeBuffer(uniformBuffer, 0, uniformData);
    },
  };

  return handles;
}

export class AlphaScaleEffect
  extends CustomShaderEffect<AlphaScaleUniforms, AlphaScaleInputs> {
  override effectName = "AlphaScale";

  constructor(
    device: GPUDevice,
    inputs: AlphaScaleInputs,
    width = 1280,
    height = 720,
    format: GPUTextureFormat = "rgba16float",
    clearColor: GPUColor = { r: 0, g: 0, b: 0, a: 1 },
    sampleMode: "nearest" | "linear" = "linear",
  ) {
    super(device, inputs, {
      factory: (deviceRef, formatRef, options) =>
        createAlphaScaleMaterial(deviceRef, formatRef, {
          ...options,
          sampleMode,
        }),
      textureInputKeys: ["src"],
      textureBindingKeys: AlphaScaleTextureNames,
      passTextureSources: AlphaScalePassTextureSources,
      passCount: 1,
      primaryTextureKey: "src",
      width,
      height,
      format,
      clearColor,
      uniformMeta: AlphaScaleUniformMeta,
    });
    this.setUniforms({
      opacity: 1.0,
    });
  }

  override setUniforms(uniforms: { opacity?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.opacity !== undefined) {
      record["opacity"] = uniforms.opacity;
    }
    super.setUniforms(record);
  }
}
