// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
import { CustomShaderEffect, type ShaderSource, type UniformDescriptor, type MaterialHandles, type ShaderUniforms, type Dynamic } from '@avtools/shader-fx/raw';
export const AlphaTimeTagVertexSource = `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct VertexOutput {
  @builtin(position) position: vec4f,
  @location(0) vUV: vec2f,
};

@vertex
fn main(@builtin(vertex_index) index: u32) -> VertexOutput {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  var uvs = array<vec2f, 3>(
    vec2f(0.0, 1.0),
    vec2f(2.0, 1.0),
    vec2f(0.0, -1.0),
  );
  var out: VertexOutput;
  out.position = vec4f(positions[index], 0.0, 1.0);
  out.vUV = uvs[index];
  return out;
}

`;
export const AlphaTimeTagFragmentSources = [
  `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct AlphaTimeTagUniforms {
  drawTime: f32,
  alphaThreshold: f32,
};

fn pass0(uv: vec2f, uniforms: AlphaTimeTagUniforms, src: texture_2d<f32>, srcSampler: sampler) -> vec4f {
  let dims = vec2i(textureDimensions(src, 0));
  let coord = clamp(vec2i(uv * vec2f(dims)), vec2i(0), dims - vec2i(1));
  let color = textureLoad(src, coord, 0);
  let alphaTime = select(0.0, uniforms.drawTime, color.a > uniforms.alphaThreshold);
  return vec4f(color.rgb, alphaTime);
}

@group(0) @binding(0) var<uniform> uniforms: AlphaTimeTagUniforms;
@group(0) @binding(1) var src: texture_2d<f32>;
@group(0) @binding(2) var srcSampler: sampler;

struct FragmentInput {
  @location(0) vUV: vec2f,
};

@fragment
fn main(input: FragmentInput) -> @location(0) vec4f {
  let uv_local = input.vUV;
  let uniforms_value = uniforms;
  let color = pass0(uv_local, uniforms_value, src, srcSampler);
  return color;
}

`, // pass0
] as const;
export const AlphaTimeTagPassCount = 1 as const;
export const AlphaTimeTagPrimaryTextureName = 'src' as const;

export const AlphaTimeTagPassTextureSources = [
  [
    { binding: 'src', source: { kind: 'input', key: 'src' } },
  ],
] as const;

export const AlphaTimeTagUniformMeta: UniformDescriptor[] = [
  {
    name: 'drawTime',
    kind: 'f32',
    bindingName: 'uniforms_drawTime',
  },
  {
    name: 'alphaThreshold',
    kind: 'f32',
    bindingName: 'uniforms_alphaThreshold',
  },
];

export interface AlphaTimeTagUniforms {
  drawTime: number;
  alphaThreshold: number;
}

export const AlphaTimeTagUniformsDefaults: AlphaTimeTagUniforms = {
  drawTime: 0,
  alphaThreshold: 0,
};

const AlphaTimeTagUniformsLayoutSize = 8;

function packAlphaTimeTagUniforms(floatView: Float32Array, intView: Int32Array, uintView: Uint32Array, floatOffset: number, value: AlphaTimeTagUniforms): void {
  {
    const base = floatOffset + 0;
    const raw = value.drawTime;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
  {
    const base = floatOffset + 1;
    const raw = value.alphaThreshold;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
}

export type AlphaTimeTagTextureName = 'src';
export const AlphaTimeTagTextureNames = ['src'] as const;
export interface AlphaTimeTagInputs {
  src: ShaderSource;
}

export type AlphaTimeTagMaterialHandles = MaterialHandles<AlphaTimeTagUniforms, AlphaTimeTagTextureName>;

export interface AlphaTimeTagMaterialOptions {
  name?: string;
  passIndex?: number;
  sampleMode?: 'nearest' | 'linear';
}

export function createAlphaTimeTagMaterial(device: GPUDevice, format: GPUTextureFormat, options: AlphaTimeTagMaterialOptions = {}): AlphaTimeTagMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(`Invalid passIndex ${passIndex} for AlphaTimeTag. Expected 0 <= passIndex < 1.`);
  }
  const uniformData = new ArrayBuffer(AlphaTimeTagUniformsLayoutSize);
  const uniformFloats = new Float32Array(uniformData);
  const uniformInts = new Int32Array(uniformData);
  const uniformUints = new Uint32Array(uniformData);
  let currentUniforms: AlphaTimeTagUniforms = { ...AlphaTimeTagUniformsDefaults };
  packAlphaTimeTagUniforms(uniformFloats, uniformInts, uniformUints, 0, currentUniforms);
  const uniformBuffer = device.createBuffer({ size: uniformData.byteLength, usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST });
  device.queue.writeBuffer(uniformBuffer, 0, uniformData);

  const bindGroupLayout = device.createBindGroupLayout({ entries: [
    { binding: 0, visibility: GPUShaderStage.FRAGMENT, buffer: { type: "uniform" } },
    { binding: 1, visibility: GPUShaderStage.FRAGMENT, texture: { sampleType: 'float' } },
    { binding: 2, visibility: GPUShaderStage.FRAGMENT, sampler: { type: 'filtering' } },
  ] });

  const pipelineLayout = device.createPipelineLayout({ bindGroupLayouts: [bindGroupLayout] });
  const vertexModule = device.createShaderModule({ code: AlphaTimeTagVertexSource });
  const fragmentModule = device.createShaderModule({ code: AlphaTimeTagFragmentSources[passIndex] });

  const pipeline = device.createRenderPipeline({
    layout: pipelineLayout,
    vertex: { module: vertexModule, entryPoint: "main" },
    fragment: { module: fragmentModule, entryPoint: "main", targets: [{ format }] },
    primitive: { topology: "triangle-list", cullMode: "none" },
  });

  const samplers: Record<string, GPUSampler> = {};
  const textureViews: Record<string, GPUTextureView> = {};
  for (const name of AlphaTimeTagTextureNames) {
    const filter = options.sampleMode ?? "linear";
    samplers[name] = device.createSampler({ magFilter: filter, minFilter: filter });
    const placeholder = device.createTexture({ size: { width: 1, height: 1 }, format, usage: GPUTextureUsage.TEXTURE_BINDING });
    textureViews[name] = placeholder.createView();
  }

  let bindGroup = device.createBindGroup({
    layout: bindGroupLayout,
    entries: [
      { binding: 0, resource: { buffer: uniformBuffer } },
      { binding: 1, resource: textureViews['src'] },
      { binding: 2, resource: samplers['src'] },
    ],
  });

  const rebuildBindGroup = () => {
    bindGroup = device.createBindGroup({
      layout: bindGroupLayout,
      entries: [
        { binding: 0, resource: { buffer: uniformBuffer } },
        { binding: 1, resource: textureViews['src'] },
        { binding: 2, resource: samplers['src'] },
      ],
    });
  };

  const handles: AlphaTimeTagMaterialHandles = {
    pipeline,
    get bindGroup() { return bindGroup; },
    setTexture: (name, texture) => {
      textureViews[name] = texture;
      rebuildBindGroup();
    },
    setUniforms: (updates) => {
      currentUniforms = { ...currentUniforms, ...updates };
      packAlphaTimeTagUniforms(uniformFloats, uniformInts, uniformUints, 0, currentUniforms);
      device.queue.writeBuffer(uniformBuffer, 0, uniformData);
    },
  };

  return handles;
}

export class AlphaTimeTagEffect extends CustomShaderEffect<AlphaTimeTagUniforms, AlphaTimeTagInputs> {
  override effectName = 'AlphaTimeTag';

  constructor(device: GPUDevice, inputs: AlphaTimeTagInputs, width = 1280, height = 720, format: GPUTextureFormat = 'rgba16float', clearColor: GPUColor = { r: 0, g: 0, b: 0, a: 1 }, sampleMode: 'nearest' | 'linear' = 'linear') {
    super(device, inputs, {
      factory: (deviceRef, formatRef, options) => createAlphaTimeTagMaterial(deviceRef, formatRef, { ...options, sampleMode }),
      textureInputKeys: ['src'],
      textureBindingKeys: AlphaTimeTagTextureNames,
      passTextureSources: AlphaTimeTagPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src',
      width,
      height,
      format,
      clearColor,
      uniformMeta: AlphaTimeTagUniformMeta,
    });
  }

  override setUniforms(uniforms: { drawTime?: Dynamic<number>, alphaThreshold?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.drawTime !== undefined) {
      record['drawTime'] = uniforms.drawTime;
    }
    if (uniforms.alphaThreshold !== undefined) {
      record['alphaThreshold'] = uniforms.alphaThreshold;
    }
    super.setUniforms(record);
  }
}

