// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
import { CustomShaderEffect, type ShaderSource, type UniformDescriptor, type MaterialHandles, type ShaderUniforms, type Dynamic } from '@avtools/shader-fx/raw';
export const ColorRemoveVertexSource = `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct VertexOutput {
  @builtin(position) position: vec4f,
  @location(0) vUV: vec2f,
};

@vertex
fn main(@builtin(vertex_index) index: u32) -> VertexOutput {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  var uvs = array<vec2f, 3>(
    vec2f(0.0, 1.0),
    vec2f(2.0, 1.0),
    vec2f(0.0, -1.0),
  );
  var out: VertexOutput;
  out.position = vec4f(positions[index], 0.0, 1.0);
  out.vUV = uvs[index];
  return out;
}

`;
export const ColorRemoveFragmentSources = [
  `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct ColorRemoveUniforms {
  targetR: f32, // 1.0
  targetG: f32, // 1.0
  targetB: f32, // 1.0
  threshold: f32, // 0.3
  feather: f32, // 0.1
};

fn pass0(
  uv: vec2f,
  uniforms: ColorRemoveUniforms,
  src: texture_2d<f32>,
  srcSampler: sampler,
) -> vec4f {
  let color = textureSample(src, srcSampler, uv);
  let targetColor = vec3f(uniforms.targetR, uniforms.targetG, uniforms.targetB);
  let dist = distance(color.rgb, targetColor);
  let mask = smoothstep(uniforms.threshold - uniforms.feather, uniforms.threshold + uniforms.feather, dist);
  return vec4f(color.rgb * mask, color.a * mask);
}

@group(0) @binding(0) var<uniform> uniforms: ColorRemoveUniforms;
@group(0) @binding(1) var src: texture_2d<f32>;
@group(0) @binding(2) var srcSampler: sampler;

struct FragmentInput {
  @location(0) vUV: vec2f,
};

@fragment
fn main(input: FragmentInput) -> @location(0) vec4f {
  let uv_local = input.vUV;
  let uniforms_value = uniforms;
  let color = pass0(uv_local, uniforms_value, src, srcSampler);
  return color;
}

`, // pass0
] as const;
export const ColorRemovePassCount = 1 as const;
export const ColorRemovePrimaryTextureName = 'src' as const;

export const ColorRemovePassTextureSources = [
  [
    { binding: 'src', source: { kind: 'input', key: 'src' } },
  ],
] as const;

export const ColorRemoveUniformMeta: UniformDescriptor[] = [
  {
    name: 'targetR',
    kind: 'f32',
    bindingName: 'uniforms_targetR',
    default: 1.0,
  },
  {
    name: 'targetG',
    kind: 'f32',
    bindingName: 'uniforms_targetG',
    default: 1.0,
  },
  {
    name: 'targetB',
    kind: 'f32',
    bindingName: 'uniforms_targetB',
    default: 1.0,
  },
  {
    name: 'threshold',
    kind: 'f32',
    bindingName: 'uniforms_threshold',
    default: 0.3,
  },
  {
    name: 'feather',
    kind: 'f32',
    bindingName: 'uniforms_feather',
    default: 0.1,
  },
];

export interface ColorRemoveUniforms {
  targetR: number;
  targetG: number;
  targetB: number;
  threshold: number;
  feather: number;
}

export const ColorRemoveUniformsDefaults: ColorRemoveUniforms = {
  targetR: 0,
  targetG: 0,
  targetB: 0,
  threshold: 0,
  feather: 0,
};

const ColorRemoveUniformsLayoutSize = 20;

function packColorRemoveUniforms(floatView: Float32Array, intView: Int32Array, uintView: Uint32Array, floatOffset: number, value: ColorRemoveUniforms): void {
  {
    const base = floatOffset + 0;
    const raw = value.targetR;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
  {
    const base = floatOffset + 1;
    const raw = value.targetG;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
  {
    const base = floatOffset + 2;
    const raw = value.targetB;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
  {
    const base = floatOffset + 3;
    const raw = value.threshold;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
  {
    const base = floatOffset + 4;
    const raw = value.feather;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
}

export type ColorRemoveTextureName = 'src';
export const ColorRemoveTextureNames = ['src'] as const;
export interface ColorRemoveInputs {
  src: ShaderSource;
}

export type ColorRemoveMaterialHandles = MaterialHandles<ColorRemoveUniforms, ColorRemoveTextureName>;

export interface ColorRemoveMaterialOptions {
  name?: string;
  passIndex?: number;
  sampleMode?: 'nearest' | 'linear';
}

export function createColorRemoveMaterial(device: GPUDevice, format: GPUTextureFormat, options: ColorRemoveMaterialOptions = {}): ColorRemoveMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(`Invalid passIndex ${passIndex} for ColorRemove. Expected 0 <= passIndex < 1.`);
  }
  const uniformData = new ArrayBuffer(ColorRemoveUniformsLayoutSize);
  const uniformFloats = new Float32Array(uniformData);
  const uniformInts = new Int32Array(uniformData);
  const uniformUints = new Uint32Array(uniformData);
  let currentUniforms: ColorRemoveUniforms = { ...ColorRemoveUniformsDefaults };
  packColorRemoveUniforms(uniformFloats, uniformInts, uniformUints, 0, currentUniforms);
  const uniformBuffer = device.createBuffer({ size: uniformData.byteLength, usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST });
  device.queue.writeBuffer(uniformBuffer, 0, uniformData);

  const bindGroupLayout = device.createBindGroupLayout({ entries: [
    { binding: 0, visibility: GPUShaderStage.FRAGMENT, buffer: { type: "uniform" } },
    { binding: 1, visibility: GPUShaderStage.FRAGMENT, texture: { sampleType: 'float' } },
    { binding: 2, visibility: GPUShaderStage.FRAGMENT, sampler: { type: 'filtering' } },
  ] });

  const pipelineLayout = device.createPipelineLayout({ bindGroupLayouts: [bindGroupLayout] });
  const vertexModule = device.createShaderModule({ code: ColorRemoveVertexSource });
  const fragmentModule = device.createShaderModule({ code: ColorRemoveFragmentSources[passIndex] });

  const pipeline = device.createRenderPipeline({
    layout: pipelineLayout,
    vertex: { module: vertexModule, entryPoint: "main" },
    fragment: { module: fragmentModule, entryPoint: "main", targets: [{ format }] },
    primitive: { topology: "triangle-list", cullMode: "none" },
  });

  const samplers: Record<string, GPUSampler> = {};
  const textureViews: Record<string, GPUTextureView> = {};
  for (const name of ColorRemoveTextureNames) {
    const filter = options.sampleMode ?? "linear";
    samplers[name] = device.createSampler({ magFilter: filter, minFilter: filter });
    const placeholder = device.createTexture({ size: { width: 1, height: 1 }, format, usage: GPUTextureUsage.TEXTURE_BINDING });
    textureViews[name] = placeholder.createView();
  }

  let bindGroup = device.createBindGroup({
    layout: bindGroupLayout,
    entries: [
      { binding: 0, resource: { buffer: uniformBuffer } },
      { binding: 1, resource: textureViews['src'] },
      { binding: 2, resource: samplers['src'] },
    ],
  });

  const rebuildBindGroup = () => {
    bindGroup = device.createBindGroup({
      layout: bindGroupLayout,
      entries: [
        { binding: 0, resource: { buffer: uniformBuffer } },
        { binding: 1, resource: textureViews['src'] },
        { binding: 2, resource: samplers['src'] },
      ],
    });
  };

  const handles: ColorRemoveMaterialHandles = {
    pipeline,
    get bindGroup() { return bindGroup; },
    setTexture: (name, texture) => {
      textureViews[name] = texture;
      rebuildBindGroup();
    },
    setUniforms: (updates) => {
      currentUniforms = { ...currentUniforms, ...updates };
      packColorRemoveUniforms(uniformFloats, uniformInts, uniformUints, 0, currentUniforms);
      device.queue.writeBuffer(uniformBuffer, 0, uniformData);
    },
  };

  return handles;
}

export class ColorRemoveEffect extends CustomShaderEffect<ColorRemoveUniforms, ColorRemoveInputs> {
  override effectName = 'ColorRemove';

  constructor(device: GPUDevice, inputs: ColorRemoveInputs, width = 1280, height = 720, format: GPUTextureFormat = 'rgba16float', clearColor: GPUColor = { r: 0, g: 0, b: 0, a: 1 }, sampleMode: 'nearest' | 'linear' = 'linear') {
    super(device, inputs, {
      factory: (deviceRef, formatRef, options) => createColorRemoveMaterial(deviceRef, formatRef, { ...options, sampleMode }),
      textureInputKeys: ['src'],
      textureBindingKeys: ColorRemoveTextureNames,
      passTextureSources: ColorRemovePassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src',
      width,
      height,
      format,
      clearColor,
      uniformMeta: ColorRemoveUniformMeta,
    });
    this.setUniforms({
      targetR: 1.0,
      targetG: 1.0,
      targetB: 1.0,
      threshold: 0.3,
      feather: 0.1,
    });
  }

  override setUniforms(uniforms: { targetR?: Dynamic<number>, targetG?: Dynamic<number>, targetB?: Dynamic<number>, threshold?: Dynamic<number>, feather?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.targetR !== undefined) {
      record['targetR'] = uniforms.targetR;
    }
    if (uniforms.targetG !== undefined) {
      record['targetG'] = uniforms.targetG;
    }
    if (uniforms.targetB !== undefined) {
      record['targetB'] = uniforms.targetB;
    }
    if (uniforms.threshold !== undefined) {
      record['threshold'] = uniforms.threshold;
    }
    if (uniforms.feather !== undefined) {
      record['feather'] = uniforms.feather;
    }
    super.setUniforms(record);
  }
}

