// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
import { CustomShaderEffect, type ShaderSource, type UniformDescriptor, type MaterialHandles, type ShaderUniforms, type Dynamic } from '@avtools/shader-fx/raw';
export const CompositeVertexSource = `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct VertexOutput {
  @builtin(position) position: vec4f,
  @location(0) vUV: vec2f,
};

@vertex
fn main(@builtin(vertex_index) index: u32) -> VertexOutput {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  var uvs = array<vec2f, 3>(
    vec2f(0.0, 1.0),
    vec2f(2.0, 1.0),
    vec2f(0.0, -1.0),
  );
  var out: VertexOutput;
  out.position = vec4f(positions[index], 0.0, 1.0);
  out.vUV = uvs[index];
  return out;
}

`;
export const CompositeFragmentSources = [
  `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct CompositeUniforms {
  mode: u32, // 0
  opacity: f32, // 1.0
};

fn blendAdd(base: vec3f, blend: vec3f) -> vec3f {
  return min(base + blend, vec3f(1.0));
}

fn blendScreen(base: vec3f, blend: vec3f) -> vec3f {
  return 1.0 - (1.0 - base) * (1.0 - blend);
}

fn blendMultiply(base: vec3f, blend: vec3f) -> vec3f {
  return base * blend;
}

fn blendOverlay(base: vec3f, blend: vec3f) -> vec3f {
  let lo = 2.0 * base * blend;
  let hi = 1.0 - 2.0 * (1.0 - base) * (1.0 - blend);
  return select(hi, lo, base < vec3f(0.5));
}

fn pass0(
  uv: vec2f,
  uniforms: CompositeUniforms,
  src1: texture_2d<f32>,
  src1Sampler: sampler,
  src2: texture_2d<f32>,
  src2Sampler: sampler,
) -> vec4f {
  let base = textureSample(src1, src1Sampler, uv);
  let blend = textureSample(src2, src2Sampler, uv);

  var result: vec3f;
  switch uniforms.mode {
    case 1u: { result = blendScreen(base.rgb, blend.rgb); }
    case 2u: { result = blendMultiply(base.rgb, blend.rgb); }
    case 3u: { result = blendOverlay(base.rgb, blend.rgb); }
    default: { result = blendAdd(base.rgb, blend.rgb); }
  }

  let blendStrength = uniforms.opacity * blend.a;
  let mixed = mix(base.rgb, result, blendStrength);
  let outAlpha = max(base.a, blendStrength);
  return vec4f(mixed, outAlpha);
}

@group(0) @binding(0) var<uniform> uniforms: CompositeUniforms;
@group(0) @binding(1) var src1: texture_2d<f32>;
@group(0) @binding(2) var src1Sampler: sampler;
@group(0) @binding(3) var src2: texture_2d<f32>;
@group(0) @binding(4) var src2Sampler: sampler;

struct FragmentInput {
  @location(0) vUV: vec2f,
};

@fragment
fn main(input: FragmentInput) -> @location(0) vec4f {
  let uv_local = input.vUV;
  let uniforms_value = uniforms;
  let color = pass0(uv_local, uniforms_value, src1, src1Sampler, src2, src2Sampler);
  return color;
}

`, // pass0
] as const;
export const CompositePassCount = 1 as const;
export const CompositePrimaryTextureName = 'src1' as const;

export const CompositePassTextureSources = [
  [
    { binding: 'src1', source: { kind: 'input', key: 'src1' } },
    { binding: 'src2', source: { kind: 'input', key: 'src2' } },
  ],
] as const;

export const CompositeUniformMeta: UniformDescriptor[] = [
  {
    name: 'mode',
    kind: 'u32',
    bindingName: 'uniforms_mode',
    default: 0,
  },
  {
    name: 'opacity',
    kind: 'f32',
    bindingName: 'uniforms_opacity',
    default: 1.0,
  },
];

export interface CompositeUniforms {
  mode: number;
  opacity: number;
}

export const CompositeUniformsDefaults: CompositeUniforms = {
  mode: 0,
  opacity: 0,
};

const CompositeUniformsLayoutSize = 8;

function packCompositeUniforms(floatView: Float32Array, intView: Int32Array, uintView: Uint32Array, floatOffset: number, value: CompositeUniforms): void {
  {
    const base = floatOffset + 0;
    const raw = value.mode;
    uintView[base] = raw !== undefined ? Math.trunc(raw as number) >>> 0 : 0;
  }
  {
    const base = floatOffset + 1;
    const raw = value.opacity;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
}

export type CompositeTextureName = 'src1' | 'src2';
export const CompositeTextureNames = ['src1', 'src2'] as const;
export interface CompositeInputs {
  src1: ShaderSource;
  src2: ShaderSource;
}

export type CompositeMaterialHandles = MaterialHandles<CompositeUniforms, CompositeTextureName>;

export interface CompositeMaterialOptions {
  name?: string;
  passIndex?: number;
  sampleMode?: 'nearest' | 'linear';
}

export function createCompositeMaterial(device: GPUDevice, format: GPUTextureFormat, options: CompositeMaterialOptions = {}): CompositeMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(`Invalid passIndex ${passIndex} for Composite. Expected 0 <= passIndex < 1.`);
  }
  const uniformData = new ArrayBuffer(CompositeUniformsLayoutSize);
  const uniformFloats = new Float32Array(uniformData);
  const uniformInts = new Int32Array(uniformData);
  const uniformUints = new Uint32Array(uniformData);
  let currentUniforms: CompositeUniforms = { ...CompositeUniformsDefaults };
  packCompositeUniforms(uniformFloats, uniformInts, uniformUints, 0, currentUniforms);
  const uniformBuffer = device.createBuffer({ size: uniformData.byteLength, usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST });
  device.queue.writeBuffer(uniformBuffer, 0, uniformData);

  const bindGroupLayout = device.createBindGroupLayout({ entries: [
    { binding: 0, visibility: GPUShaderStage.FRAGMENT, buffer: { type: "uniform" } },
    { binding: 1, visibility: GPUShaderStage.FRAGMENT, texture: { sampleType: 'float' } },
    { binding: 2, visibility: GPUShaderStage.FRAGMENT, sampler: { type: 'filtering' } },
    { binding: 3, visibility: GPUShaderStage.FRAGMENT, texture: { sampleType: 'float' } },
    { binding: 4, visibility: GPUShaderStage.FRAGMENT, sampler: { type: 'filtering' } },
  ] });

  const pipelineLayout = device.createPipelineLayout({ bindGroupLayouts: [bindGroupLayout] });
  const vertexModule = device.createShaderModule({ code: CompositeVertexSource });
  const fragmentModule = device.createShaderModule({ code: CompositeFragmentSources[passIndex] });

  const pipeline = device.createRenderPipeline({
    layout: pipelineLayout,
    vertex: { module: vertexModule, entryPoint: "main" },
    fragment: { module: fragmentModule, entryPoint: "main", targets: [{ format }] },
    primitive: { topology: "triangle-list", cullMode: "none" },
  });

  const samplers: Record<string, GPUSampler> = {};
  const textureViews: Record<string, GPUTextureView> = {};
  for (const name of CompositeTextureNames) {
    const filter = options.sampleMode ?? "linear";
    samplers[name] = device.createSampler({ magFilter: filter, minFilter: filter });
    const placeholder = device.createTexture({ size: { width: 1, height: 1 }, format, usage: GPUTextureUsage.TEXTURE_BINDING });
    textureViews[name] = placeholder.createView();
  }

  let bindGroup = device.createBindGroup({
    layout: bindGroupLayout,
    entries: [
      { binding: 0, resource: { buffer: uniformBuffer } },
      { binding: 1, resource: textureViews['src1'] },
      { binding: 2, resource: samplers['src1'] },
      { binding: 3, resource: textureViews['src2'] },
      { binding: 4, resource: samplers['src2'] },
    ],
  });

  const rebuildBindGroup = () => {
    bindGroup = device.createBindGroup({
      layout: bindGroupLayout,
      entries: [
        { binding: 0, resource: { buffer: uniformBuffer } },
        { binding: 1, resource: textureViews['src1'] },
        { binding: 2, resource: samplers['src1'] },
        { binding: 3, resource: textureViews['src2'] },
        { binding: 4, resource: samplers['src2'] },
      ],
    });
  };

  const handles: CompositeMaterialHandles = {
    pipeline,
    get bindGroup() { return bindGroup; },
    setTexture: (name, texture) => {
      textureViews[name] = texture;
      rebuildBindGroup();
    },
    setUniforms: (updates) => {
      currentUniforms = { ...currentUniforms, ...updates };
      packCompositeUniforms(uniformFloats, uniformInts, uniformUints, 0, currentUniforms);
      device.queue.writeBuffer(uniformBuffer, 0, uniformData);
    },
  };

  return handles;
}

export class CompositeEffect extends CustomShaderEffect<CompositeUniforms, CompositeInputs> {
  override effectName = 'Composite';

  constructor(device: GPUDevice, inputs: CompositeInputs, width = 1280, height = 720, format: GPUTextureFormat = 'rgba16float', clearColor: GPUColor = { r: 0, g: 0, b: 0, a: 1 }, sampleMode: 'nearest' | 'linear' = 'linear') {
    super(device, inputs, {
      factory: (deviceRef, formatRef, options) => createCompositeMaterial(deviceRef, formatRef, { ...options, sampleMode }),
      textureInputKeys: ['src1', 'src2'],
      textureBindingKeys: CompositeTextureNames,
      passTextureSources: CompositePassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src1',
      width,
      height,
      format,
      clearColor,
      uniformMeta: CompositeUniformMeta,
    });
    this.setUniforms({
      mode: 0,
      opacity: 1.0,
    });
  }

  override setUniforms(uniforms: { mode?: Dynamic<number>, opacity?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.mode !== undefined) {
      record['mode'] = uniforms.mode;
    }
    if (uniforms.opacity !== undefined) {
      record['opacity'] = uniforms.opacity;
    }
    super.setUniforms(record);
  }
}

