// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
import { CustomShaderEffect, type ShaderSource, type UniformDescriptor, type MaterialHandles, type ShaderUniforms, type Dynamic } from '@avtools/shader-fx/raw';
export const FloodFillStepVertexSource = `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct VertexOutput {
  @builtin(position) position: vec4f,
  @location(0) vUV: vec2f,
};

@vertex
fn main(@builtin(vertex_index) index: u32) -> VertexOutput {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  var uvs = array<vec2f, 3>(
    vec2f(0.0, 1.0),
    vec2f(2.0, 1.0),
    vec2f(0.0, -1.0),
  );
  var out: VertexOutput;
  out.position = vec4f(positions[index], 0.0, 1.0);
  out.vUV = uvs[index];
  return out;
}

`;
export const FloodFillStepFragmentSources = [
  `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct FloodFillStepUniforms {
  diskRadius: f32,
  useDisk: f32,
  skipDistance: f32,
  currentPhase: f32,
};

const RECENCY_TAG_EPSILON: f32 = 0.00048828125;

fn decodeRecencyTag(tag: f32) -> f32 {
  return clamp((tag - RECENCY_TAG_EPSILON) / (1.0 - RECENCY_TAG_EPSILON), 0.0, 1.0);
}

fn wrappedAge(currentPhase: f32, tag: f32) -> f32 {
  let candidatePhase = decodeRecencyTag(tag);
  return fract(currentPhase - candidatePhase + 1.0);
}

fn pass0(uv: vec2f, uniforms: FloodFillStepUniforms, seed: texture_2d<f32>, seedSampler: sampler, feedback: texture_2d<f32>, feedbackSampler: sampler) -> vec4f {
  let seedDims = vec2i(textureDimensions(seed, 0));
  let feedbackDims = vec2i(textureDimensions(feedback, 0));
  let seedCoord = clamp(vec2i(uv * vec2f(seedDims)), vec2i(0), seedDims - vec2i(1));
  let feedbackCoord = clamp(vec2i(uv * vec2f(feedbackDims)), vec2i(0), feedbackDims - vec2i(1));

  let seedColor = textureLoad(seed, seedCoord, 0);
  let feedbackColor = textureLoad(feedback, feedbackCoord, 0);

  var chosenFeedback = feedbackColor;
  var bestAge = select(2.0, wrappedAge(uniforms.currentPhase, feedbackColor.a), feedbackColor.a > 0.0);

  let useDisk = uniforms.useDisk > 0.5;
  let r = select(1, i32(max(1.0, uniforms.diskRadius)), useDisk);
  let rSq = uniforms.diskRadius * uniforms.diskRadius;
  let stride = max(1.0, uniforms.skipDistance + 1.0);

  for (var y = -r; y <= r; y = y + 1) {
    for (var x = -r; x <= r; x = x + 1) {
      if (useDisk) {
        let d = f32(x * x + y * y);
        if (d > rSq) { continue; }
      }
      let sampleOffset = vec2i(round(vec2f(f32(x), f32(y)) * stride));
      let neighborCoord = clamp(
        feedbackCoord + sampleOffset,
        vec2i(0),
        feedbackDims - vec2i(1),
      );
      let candidate = textureLoad(feedback, neighborCoord, 0);
      if (candidate.a <= 0.0) {
        continue;
      }
      let candidateAge = wrappedAge(uniforms.currentPhase, candidate.a);
      if (candidateAge < bestAge) {
        bestAge = candidateAge;
        chosenFeedback = candidate;
      }
    }
  }

  if (seedColor.a > 0.0) {
    return seedColor;
  }

  return chosenFeedback;
}

@group(0) @binding(0) var<uniform> uniforms: FloodFillStepUniforms;
@group(0) @binding(1) var seed: texture_2d<f32>;
@group(0) @binding(2) var seedSampler: sampler;
@group(0) @binding(3) var feedback: texture_2d<f32>;
@group(0) @binding(4) var feedbackSampler: sampler;

struct FragmentInput {
  @location(0) vUV: vec2f,
};

@fragment
fn main(input: FragmentInput) -> @location(0) vec4f {
  let uv_local = input.vUV;
  let uniforms_value = uniforms;
  let color = pass0(uv_local, uniforms_value, seed, seedSampler, feedback, feedbackSampler);
  return color;
}

`, // pass0
] as const;
export const FloodFillStepPassCount = 1 as const;
export const FloodFillStepPrimaryTextureName = 'seed' as const;

export const FloodFillStepPassTextureSources = [
  [
    { binding: 'seed', source: { kind: 'input', key: 'seed' } },
    { binding: 'feedback', source: { kind: 'input', key: 'feedback' } },
  ],
] as const;

export const FloodFillStepUniformMeta: UniformDescriptor[] = [
  {
    name: 'diskRadius',
    kind: 'f32',
    bindingName: 'uniforms_diskRadius',
  },
  {
    name: 'useDisk',
    kind: 'f32',
    bindingName: 'uniforms_useDisk',
  },
  {
    name: 'skipDistance',
    kind: 'f32',
    bindingName: 'uniforms_skipDistance',
  },
  {
    name: 'currentPhase',
    kind: 'f32',
    bindingName: 'uniforms_currentPhase',
  },
];

export interface FloodFillStepUniforms {
  diskRadius: number;
  useDisk: number;
  skipDistance: number;
  currentPhase: number;
}

export const FloodFillStepUniformsDefaults: FloodFillStepUniforms = {
  diskRadius: 0,
  useDisk: 0,
  skipDistance: 0,
  currentPhase: 0,
};

const FloodFillStepUniformsLayoutSize = 16;

function packFloodFillStepUniforms(floatView: Float32Array, intView: Int32Array, uintView: Uint32Array, floatOffset: number, value: FloodFillStepUniforms): void {
  {
    const base = floatOffset + 0;
    const raw = value.diskRadius;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
  {
    const base = floatOffset + 1;
    const raw = value.useDisk;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
  {
    const base = floatOffset + 2;
    const raw = value.skipDistance;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
  {
    const base = floatOffset + 3;
    const raw = value.currentPhase;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
}

export type FloodFillStepTextureName = 'seed' | 'feedback';
export const FloodFillStepTextureNames = ['seed', 'feedback'] as const;
export interface FloodFillStepInputs {
  seed: ShaderSource;
  feedback: ShaderSource;
}

export type FloodFillStepMaterialHandles = MaterialHandles<FloodFillStepUniforms, FloodFillStepTextureName>;

export interface FloodFillStepMaterialOptions {
  name?: string;
  passIndex?: number;
  sampleMode?: 'nearest' | 'linear';
}

export function createFloodFillStepMaterial(device: GPUDevice, format: GPUTextureFormat, options: FloodFillStepMaterialOptions = {}): FloodFillStepMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(`Invalid passIndex ${passIndex} for FloodFillStep. Expected 0 <= passIndex < 1.`);
  }
  const uniformData = new ArrayBuffer(FloodFillStepUniformsLayoutSize);
  const uniformFloats = new Float32Array(uniformData);
  const uniformInts = new Int32Array(uniformData);
  const uniformUints = new Uint32Array(uniformData);
  let currentUniforms: FloodFillStepUniforms = { ...FloodFillStepUniformsDefaults };
  packFloodFillStepUniforms(uniformFloats, uniformInts, uniformUints, 0, currentUniforms);
  const uniformBuffer = device.createBuffer({ size: uniformData.byteLength, usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST });
  device.queue.writeBuffer(uniformBuffer, 0, uniformData);

  const bindGroupLayout = device.createBindGroupLayout({ entries: [
    { binding: 0, visibility: GPUShaderStage.FRAGMENT, buffer: { type: "uniform" } },
    { binding: 1, visibility: GPUShaderStage.FRAGMENT, texture: { sampleType: 'float' } },
    { binding: 2, visibility: GPUShaderStage.FRAGMENT, sampler: { type: 'filtering' } },
    { binding: 3, visibility: GPUShaderStage.FRAGMENT, texture: { sampleType: 'float' } },
    { binding: 4, visibility: GPUShaderStage.FRAGMENT, sampler: { type: 'filtering' } },
  ] });

  const pipelineLayout = device.createPipelineLayout({ bindGroupLayouts: [bindGroupLayout] });
  const vertexModule = device.createShaderModule({ code: FloodFillStepVertexSource });
  const fragmentModule = device.createShaderModule({ code: FloodFillStepFragmentSources[passIndex] });

  const pipeline = device.createRenderPipeline({
    layout: pipelineLayout,
    vertex: { module: vertexModule, entryPoint: "main" },
    fragment: { module: fragmentModule, entryPoint: "main", targets: [{ format }] },
    primitive: { topology: "triangle-list", cullMode: "none" },
  });

  const samplers: Record<string, GPUSampler> = {};
  const textureViews: Record<string, GPUTextureView> = {};
  for (const name of FloodFillStepTextureNames) {
    const filter = options.sampleMode ?? "linear";
    samplers[name] = device.createSampler({ magFilter: filter, minFilter: filter });
    const placeholder = device.createTexture({ size: { width: 1, height: 1 }, format, usage: GPUTextureUsage.TEXTURE_BINDING });
    textureViews[name] = placeholder.createView();
  }

  let bindGroup = device.createBindGroup({
    layout: bindGroupLayout,
    entries: [
      { binding: 0, resource: { buffer: uniformBuffer } },
      { binding: 1, resource: textureViews['seed'] },
      { binding: 2, resource: samplers['seed'] },
      { binding: 3, resource: textureViews['feedback'] },
      { binding: 4, resource: samplers['feedback'] },
    ],
  });

  const rebuildBindGroup = () => {
    bindGroup = device.createBindGroup({
      layout: bindGroupLayout,
      entries: [
        { binding: 0, resource: { buffer: uniformBuffer } },
        { binding: 1, resource: textureViews['seed'] },
        { binding: 2, resource: samplers['seed'] },
        { binding: 3, resource: textureViews['feedback'] },
        { binding: 4, resource: samplers['feedback'] },
      ],
    });
  };

  const handles: FloodFillStepMaterialHandles = {
    pipeline,
    get bindGroup() { return bindGroup; },
    setTexture: (name, texture) => {
      textureViews[name] = texture;
      rebuildBindGroup();
    },
    setUniforms: (updates) => {
      currentUniforms = { ...currentUniforms, ...updates };
      packFloodFillStepUniforms(uniformFloats, uniformInts, uniformUints, 0, currentUniforms);
      device.queue.writeBuffer(uniformBuffer, 0, uniformData);
    },
  };

  return handles;
}

export class FloodFillStepEffect extends CustomShaderEffect<FloodFillStepUniforms, FloodFillStepInputs> {
  override effectName = 'FloodFillStep';

  constructor(device: GPUDevice, inputs: FloodFillStepInputs, width = 1280, height = 720, format: GPUTextureFormat = 'rgba16float', clearColor: GPUColor = { r: 0, g: 0, b: 0, a: 1 }, sampleMode: 'nearest' | 'linear' = 'linear') {
    super(device, inputs, {
      factory: (deviceRef, formatRef, options) => createFloodFillStepMaterial(deviceRef, formatRef, { ...options, sampleMode }),
      textureInputKeys: ['seed', 'feedback'],
      textureBindingKeys: FloodFillStepTextureNames,
      passTextureSources: FloodFillStepPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'seed',
      width,
      height,
      format,
      clearColor,
      uniformMeta: FloodFillStepUniformMeta,
    });
  }

  override setUniforms(uniforms: { diskRadius?: Dynamic<number>, useDisk?: Dynamic<number>, skipDistance?: Dynamic<number>, currentPhase?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.diskRadius !== undefined) {
      record['diskRadius'] = uniforms.diskRadius;
    }
    if (uniforms.useDisk !== undefined) {
      record['useDisk'] = uniforms.useDisk;
    }
    if (uniforms.skipDistance !== undefined) {
      record['skipDistance'] = uniforms.skipDistance;
    }
    if (uniforms.currentPhase !== undefined) {
      record['currentPhase'] = uniforms.currentPhase;
    }
    super.setUniforms(record);
  }
}

