// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
import { CustomShaderEffect, type ShaderSource, type UniformDescriptor, type MaterialHandles } from '@avtools/shader-fx/raw';
export const FloodFillDisplayVertexSource = `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct VertexOutput {
  @builtin(position) position: vec4f,
  @location(0) vUV: vec2f,
};

@vertex
fn main(@builtin(vertex_index) index: u32) -> VertexOutput {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  var uvs = array<vec2f, 3>(
    vec2f(0.0, 1.0),
    vec2f(2.0, 1.0),
    vec2f(0.0, -1.0),
  );
  var out: VertexOutput;
  out.position = vec4f(positions[index], 0.0, 1.0);
  out.vUV = uvs[index];
  return out;
}

`;
export const FloodFillDisplayFragmentSources = [
  `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
fn pass0(uv: vec2f, src: texture_2d<f32>, srcSampler: sampler) -> vec4f {
  let dims = vec2i(textureDimensions(src, 0));
  let coord = clamp(vec2i(uv * vec2f(dims)), vec2i(0), dims - vec2i(1));
  let color = textureLoad(src, coord, 0);
  let alpha = select(0.0, 1.0, color.a > 0.0);
  return vec4f(color.rgb, alpha);
}

@group(0) @binding(0) var src: texture_2d<f32>;
@group(0) @binding(1) var srcSampler: sampler;

struct FragmentInput {
  @location(0) vUV: vec2f,
};

@fragment
fn main(input: FragmentInput) -> @location(0) vec4f {
  let uv_local = input.vUV;
  let color = pass0(uv_local, src, srcSampler);
  return color;
}

`, // pass0
] as const;
export const FloodFillDisplayPassCount = 1 as const;
export const FloodFillDisplayPrimaryTextureName = 'src' as const;

export const FloodFillDisplayPassTextureSources = [
  [
    { binding: 'src', source: { kind: 'input', key: 'src' } },
  ],
] as const;

export const FloodFillDisplayUniformMeta: UniformDescriptor[] = [];

export type FloodFillDisplayUniforms = Record<string, never>;
export const FloodFillDisplayUniformsDefaults = {};

export type FloodFillDisplayTextureName = 'src';
export const FloodFillDisplayTextureNames = ['src'] as const;
export interface FloodFillDisplayInputs {
  src: ShaderSource;
}

export type FloodFillDisplayMaterialHandles = MaterialHandles<FloodFillDisplayUniforms, FloodFillDisplayTextureName>;

export interface FloodFillDisplayMaterialOptions {
  name?: string;
  passIndex?: number;
}

export function createFloodFillDisplayMaterial(device: GPUDevice, format: GPUTextureFormat, options: FloodFillDisplayMaterialOptions = {}): FloodFillDisplayMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(`Invalid passIndex ${passIndex} for FloodFillDisplay. Expected 0 <= passIndex < 1.`);
  }
  const bindGroupLayout = device.createBindGroupLayout({ entries: [
    { binding: 0, visibility: GPUShaderStage.FRAGMENT, texture: { sampleType: 'float' } },
    { binding: 1, visibility: GPUShaderStage.FRAGMENT, sampler: { type: 'filtering' } },
  ] });

  const pipelineLayout = device.createPipelineLayout({ bindGroupLayouts: [bindGroupLayout] });
  const vertexModule = device.createShaderModule({ code: FloodFillDisplayVertexSource });
  const fragmentModule = device.createShaderModule({ code: FloodFillDisplayFragmentSources[passIndex] });

  const pipeline = device.createRenderPipeline({
    layout: pipelineLayout,
    vertex: { module: vertexModule, entryPoint: "main" },
    fragment: { module: fragmentModule, entryPoint: "main", targets: [{ format }] },
    primitive: { topology: "triangle-list", cullMode: "none" },
  });

  const samplers: Record<string, GPUSampler> = {};
  const textureViews: Record<string, GPUTextureView> = {};
  for (const name of FloodFillDisplayTextureNames) {
    samplers[name] = device.createSampler({ magFilter: "linear", minFilter: "linear" });
    const placeholder = device.createTexture({ size: { width: 1, height: 1 }, format, usage: GPUTextureUsage.TEXTURE_BINDING });
    textureViews[name] = placeholder.createView();
  }

  let bindGroup = device.createBindGroup({
    layout: bindGroupLayout,
    entries: [
      { binding: 0, resource: textureViews['src'] },
      { binding: 1, resource: samplers['src'] },
    ],
  });

  const rebuildBindGroup = () => {
    bindGroup = device.createBindGroup({
      layout: bindGroupLayout,
      entries: [
        { binding: 0, resource: textureViews['src'] },
        { binding: 1, resource: samplers['src'] },
      ],
    });
  };

  const handles: FloodFillDisplayMaterialHandles = {
    pipeline,
    get bindGroup() { return bindGroup; },
    setTexture: (name, texture) => {
      textureViews[name] = texture;
      rebuildBindGroup();
    },
    setUniforms: () => {},
  };

  return handles;
}

export class FloodFillDisplayEffect extends CustomShaderEffect<FloodFillDisplayUniforms, FloodFillDisplayInputs> {
  override effectName = 'FloodFillDisplay';

  constructor(device: GPUDevice, inputs: FloodFillDisplayInputs, width = 1280, height = 720, format: GPUTextureFormat = 'rgba16float', clearColor: GPUColor = { r: 0, g: 0, b: 0, a: 1 }) {
    super(device, inputs, {
      factory: (deviceRef, formatRef, options) => createFloodFillDisplayMaterial(deviceRef, formatRef, options),
      textureInputKeys: ['src'],
      textureBindingKeys: FloodFillDisplayTextureNames,
      passTextureSources: FloodFillDisplayPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src',
      width,
      height,
      format,
      clearColor,
      uniformMeta: FloodFillDisplayUniformMeta,
    });
  }
}

