// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
import { CustomShaderEffect, type ShaderSource, type UniformDescriptor, type MaterialHandles, type ShaderUniforms, type Dynamic } from '@avtools/shader-fx/raw';
export const GrainVertexSource = `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct VertexOutput {
  @builtin(position) position: vec4f,
  @location(0) vUV: vec2f,
};

@vertex
fn main(@builtin(vertex_index) index: u32) -> VertexOutput {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  var uvs = array<vec2f, 3>(
    vec2f(0.0, 1.0),
    vec2f(2.0, 1.0),
    vec2f(0.0, -1.0),
  );
  var out: VertexOutput;
  out.position = vec4f(positions[index], 0.0, 1.0);
  out.vUV = uvs[index];
  return out;
}

`;
export const GrainFragmentSources = [
  `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct GrainUniforms {
  deviationPixels: f32,
  time: f32,
  frameNumber: f32,
  cellSize: f32,
};

fn hashU32(value: u32) -> u32 {
  var h = value;
  h = h ^ (h >> 16u);
  h = h * 0x7feb352du;
  h = h ^ (h >> 15u);
  h = h * 0x846ca68bu;
  h = h ^ (h >> 16u);
  return h;
}

fn hashCell(cell: vec2u, frame: u32, salt: u32) -> f32 {
  let mixed = cell.x * 0x8da6b343u ^
    cell.y * 0xd8163841u ^
    frame * 0xcb1ab31fu ^
    salt;
  return f32(hashU32(mixed) & 0x00ffffffu) / 16777215.0;
}

fn pass0(uv: vec2f, uniforms: GrainUniforms, src: texture_2d<f32>, srcSampler: sampler) -> vec4f {
  let dims = vec2f(textureDimensions(src, 0));
  let pixel = floor(uv * dims);
  let cellSize = max(uniforms.cellSize, 1.0);
  let grainCell = vec2u(floor(pixel / vec2f(cellSize)));
  let frame = u32(floor(max(uniforms.frameNumber, 0.0))) % 1048576u;
  let jitter = vec2f(
    hashCell(grainCell, frame, 0x9e3779b9u),
    hashCell(grainCell, frame, 0x85ebca6bu)
  ) * 2.0 - vec2f(1.0);
  let samplePixel = clamp(
    pixel + jitter * max(uniforms.deviationPixels, 0.0),
    vec2f(0.5),
    dims - vec2f(0.5)
  );
  let sampleUv = (samplePixel + vec2f(0.5)) / dims;
  return textureSample(src, srcSampler, sampleUv);
}

@group(0) @binding(0) var<uniform> uniforms: GrainUniforms;
@group(0) @binding(1) var src: texture_2d<f32>;
@group(0) @binding(2) var srcSampler: sampler;

struct FragmentInput {
  @location(0) vUV: vec2f,
};

@fragment
fn main(input: FragmentInput) -> @location(0) vec4f {
  let uv_local = input.vUV;
  let uniforms_value = uniforms;
  let color = pass0(uv_local, uniforms_value, src, srcSampler);
  return color;
}

`, // pass0
] as const;
export const GrainPassCount = 1 as const;
export const GrainPrimaryTextureName = 'src' as const;

export const GrainPassTextureSources = [
  [
    { binding: 'src', source: { kind: 'input', key: 'src' } },
  ],
] as const;

export const GrainUniformMeta: UniformDescriptor[] = [
  {
    name: 'deviationPixels',
    kind: 'f32',
    bindingName: 'uniforms_deviationPixels',
  },
  {
    name: 'time',
    kind: 'f32',
    bindingName: 'uniforms_time',
  },
  {
    name: 'frameNumber',
    kind: 'f32',
    bindingName: 'uniforms_frameNumber',
  },
  {
    name: 'cellSize',
    kind: 'f32',
    bindingName: 'uniforms_cellSize',
  },
];

export interface GrainUniforms {
  deviationPixels: number;
  time: number;
  frameNumber: number;
  cellSize: number;
}

export const GrainUniformsDefaults: GrainUniforms = {
  deviationPixels: 0,
  time: 0,
  frameNumber: 0,
  cellSize: 0,
};

const GrainUniformsLayoutSize = 16;

function packGrainUniforms(floatView: Float32Array, intView: Int32Array, uintView: Uint32Array, floatOffset: number, value: GrainUniforms): void {
  {
    const base = floatOffset + 0;
    const raw = value.deviationPixels;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
  {
    const base = floatOffset + 1;
    const raw = value.time;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
  {
    const base = floatOffset + 2;
    const raw = value.frameNumber;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
  {
    const base = floatOffset + 3;
    const raw = value.cellSize;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
}

export type GrainTextureName = 'src';
export const GrainTextureNames = ['src'] as const;
export interface GrainInputs {
  src: ShaderSource;
}

export type GrainMaterialHandles = MaterialHandles<GrainUniforms, GrainTextureName>;

export interface GrainMaterialOptions {
  name?: string;
  passIndex?: number;
  sampleMode?: 'nearest' | 'linear';
}

export function createGrainMaterial(device: GPUDevice, format: GPUTextureFormat, options: GrainMaterialOptions = {}): GrainMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(`Invalid passIndex ${passIndex} for Grain. Expected 0 <= passIndex < 1.`);
  }
  const uniformData = new ArrayBuffer(GrainUniformsLayoutSize);
  const uniformFloats = new Float32Array(uniformData);
  const uniformInts = new Int32Array(uniformData);
  const uniformUints = new Uint32Array(uniformData);
  let currentUniforms: GrainUniforms = { ...GrainUniformsDefaults };
  packGrainUniforms(uniformFloats, uniformInts, uniformUints, 0, currentUniforms);
  const uniformBuffer = device.createBuffer({ size: uniformData.byteLength, usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST });
  device.queue.writeBuffer(uniformBuffer, 0, uniformData);

  const bindGroupLayout = device.createBindGroupLayout({ entries: [
    { binding: 0, visibility: GPUShaderStage.FRAGMENT, buffer: { type: "uniform" } },
    { binding: 1, visibility: GPUShaderStage.FRAGMENT, texture: { sampleType: 'float' } },
    { binding: 2, visibility: GPUShaderStage.FRAGMENT, sampler: { type: 'filtering' } },
  ] });

  const pipelineLayout = device.createPipelineLayout({ bindGroupLayouts: [bindGroupLayout] });
  const vertexModule = device.createShaderModule({ code: GrainVertexSource });
  const fragmentModule = device.createShaderModule({ code: GrainFragmentSources[passIndex] });

  const pipeline = device.createRenderPipeline({
    layout: pipelineLayout,
    vertex: { module: vertexModule, entryPoint: "main" },
    fragment: { module: fragmentModule, entryPoint: "main", targets: [{ format }] },
    primitive: { topology: "triangle-list", cullMode: "none" },
  });

  const samplers: Record<string, GPUSampler> = {};
  const textureViews: Record<string, GPUTextureView> = {};
  for (const name of GrainTextureNames) {
    const filter = options.sampleMode ?? "linear";
    samplers[name] = device.createSampler({ magFilter: filter, minFilter: filter });
    const placeholder = device.createTexture({ size: { width: 1, height: 1 }, format, usage: GPUTextureUsage.TEXTURE_BINDING });
    textureViews[name] = placeholder.createView();
  }

  let bindGroup = device.createBindGroup({
    layout: bindGroupLayout,
    entries: [
      { binding: 0, resource: { buffer: uniformBuffer } },
      { binding: 1, resource: textureViews['src'] },
      { binding: 2, resource: samplers['src'] },
    ],
  });

  const rebuildBindGroup = () => {
    bindGroup = device.createBindGroup({
      layout: bindGroupLayout,
      entries: [
        { binding: 0, resource: { buffer: uniformBuffer } },
        { binding: 1, resource: textureViews['src'] },
        { binding: 2, resource: samplers['src'] },
      ],
    });
  };

  const handles: GrainMaterialHandles = {
    pipeline,
    get bindGroup() { return bindGroup; },
    setTexture: (name, texture) => {
      textureViews[name] = texture;
      rebuildBindGroup();
    },
    setUniforms: (updates) => {
      currentUniforms = { ...currentUniforms, ...updates };
      packGrainUniforms(uniformFloats, uniformInts, uniformUints, 0, currentUniforms);
      device.queue.writeBuffer(uniformBuffer, 0, uniformData);
    },
  };

  return handles;
}

export class GrainEffect extends CustomShaderEffect<GrainUniforms, GrainInputs> {
  override effectName = 'Grain';

  constructor(device: GPUDevice, inputs: GrainInputs, width = 1280, height = 720, format: GPUTextureFormat = 'rgba16float', clearColor: GPUColor = { r: 0, g: 0, b: 0, a: 1 }, sampleMode: 'nearest' | 'linear' = 'linear') {
    super(device, inputs, {
      factory: (deviceRef, formatRef, options) => createGrainMaterial(deviceRef, formatRef, { ...options, sampleMode }),
      textureInputKeys: ['src'],
      textureBindingKeys: GrainTextureNames,
      passTextureSources: GrainPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src',
      width,
      height,
      format,
      clearColor,
      uniformMeta: GrainUniformMeta,
    });
  }

  override setUniforms(uniforms: { deviationPixels?: Dynamic<number>, time?: Dynamic<number>, frameNumber?: Dynamic<number>, cellSize?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.deviationPixels !== undefined) {
      record['deviationPixels'] = uniforms.deviationPixels;
    }
    if (uniforms.time !== undefined) {
      record['time'] = uniforms.time;
    }
    if (uniforms.frameNumber !== undefined) {
      record['frameNumber'] = uniforms.frameNumber;
    }
    if (uniforms.cellSize !== undefined) {
      record['cellSize'] = uniforms.cellSize;
    }
    super.setUniforms(record);
  }
}

