// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
import { CustomShaderEffect, type ShaderSource, type UniformDescriptor, type MaterialHandles, type ShaderUniforms, type Dynamic } from '@avtools/shader-fx/raw';
export const MathOpVertexSource = `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct VertexOutput {
  @builtin(position) position: vec4f,
  @location(0) vUV: vec2f,
};

@vertex
fn main(@builtin(vertex_index) index: u32) -> VertexOutput {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  var uvs = array<vec2f, 3>(
    vec2f(0.0, 1.0),
    vec2f(2.0, 1.0),
    vec2f(0.0, -1.0),
  );
  var out: VertexOutput;
  out.position = vec4f(positions[index], 0.0, 1.0);
  out.vUV = uvs[index];
  return out;
}

`;
export const MathOpFragmentSources = [
  `// Auto-generated by raw WGSL fragment generator. DO NOT EDIT.
struct MathOpUniforms {
  mult: f32,
};

fn pass0(uv: vec2f, uniforms: MathOpUniforms, src: texture_2d<f32>, srcSampler: sampler) -> vec4f {
  let color = textureSample(src, srcSampler, uv);
  return color * uniforms.mult;
}

@group(0) @binding(0) var<uniform> uniforms: MathOpUniforms;
@group(0) @binding(1) var src: texture_2d<f32>;
@group(0) @binding(2) var srcSampler: sampler;

struct FragmentInput {
  @location(0) vUV: vec2f,
};

@fragment
fn main(input: FragmentInput) -> @location(0) vec4f {
  let uv_local = input.vUV;
  let uniforms_value = uniforms;
  let color = pass0(uv_local, uniforms_value, src, srcSampler);
  return color;
}

`, // pass0
] as const;
export const MathOpPassCount = 1 as const;
export const MathOpPrimaryTextureName = 'src' as const;

export const MathOpPassTextureSources = [
  [
    { binding: 'src', source: { kind: 'input', key: 'src' } },
  ],
] as const;

export const MathOpUniformMeta: UniformDescriptor[] = [
  {
    name: 'mult',
    kind: 'f32',
    bindingName: 'uniforms_mult',
  },
];

export interface MathOpUniforms {
  mult: number;
}

export const MathOpUniformsDefaults: MathOpUniforms = {
  mult: 0,
};

const MathOpUniformsLayoutSize = 4;

function packMathOpUniforms(floatView: Float32Array, intView: Int32Array, uintView: Uint32Array, floatOffset: number, value: MathOpUniforms): void {
  {
    const base = floatOffset + 0;
    const raw = value.mult;
    floatView[base] = raw !== undefined ? Number(raw) : 0;
  }
}

export type MathOpTextureName = 'src';
export const MathOpTextureNames = ['src'] as const;
export interface MathOpInputs {
  src: ShaderSource;
}

export type MathOpMaterialHandles = MaterialHandles<MathOpUniforms, MathOpTextureName>;

export interface MathOpMaterialOptions {
  name?: string;
  passIndex?: number;
  sampleMode?: 'nearest' | 'linear';
}

export function createMathOpMaterial(device: GPUDevice, format: GPUTextureFormat, options: MathOpMaterialOptions = {}): MathOpMaterialHandles {
  const passIndex = options.passIndex ?? 0;
  if (passIndex < 0 || passIndex >= 1) {
    throw new Error(`Invalid passIndex ${passIndex} for MathOp. Expected 0 <= passIndex < 1.`);
  }
  const uniformData = new ArrayBuffer(MathOpUniformsLayoutSize);
  const uniformFloats = new Float32Array(uniformData);
  const uniformInts = new Int32Array(uniformData);
  const uniformUints = new Uint32Array(uniformData);
  let currentUniforms: MathOpUniforms = { ...MathOpUniformsDefaults };
  packMathOpUniforms(uniformFloats, uniformInts, uniformUints, 0, currentUniforms);
  const uniformBuffer = device.createBuffer({ size: uniformData.byteLength, usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST });
  device.queue.writeBuffer(uniformBuffer, 0, uniformData);

  const bindGroupLayout = device.createBindGroupLayout({ entries: [
    { binding: 0, visibility: GPUShaderStage.FRAGMENT, buffer: { type: "uniform" } },
    { binding: 1, visibility: GPUShaderStage.FRAGMENT, texture: { sampleType: 'float' } },
    { binding: 2, visibility: GPUShaderStage.FRAGMENT, sampler: { type: 'filtering' } },
  ] });

  const pipelineLayout = device.createPipelineLayout({ bindGroupLayouts: [bindGroupLayout] });
  const vertexModule = device.createShaderModule({ code: MathOpVertexSource });
  const fragmentModule = device.createShaderModule({ code: MathOpFragmentSources[passIndex] });

  const pipeline = device.createRenderPipeline({
    layout: pipelineLayout,
    vertex: { module: vertexModule, entryPoint: "main" },
    fragment: { module: fragmentModule, entryPoint: "main", targets: [{ format }] },
    primitive: { topology: "triangle-list", cullMode: "none" },
  });

  const samplers: Record<string, GPUSampler> = {};
  const textureViews: Record<string, GPUTextureView> = {};
  for (const name of MathOpTextureNames) {
    const filter = options.sampleMode ?? "linear";
    samplers[name] = device.createSampler({ magFilter: filter, minFilter: filter });
    const placeholder = device.createTexture({ size: { width: 1, height: 1 }, format, usage: GPUTextureUsage.TEXTURE_BINDING });
    textureViews[name] = placeholder.createView();
  }

  let bindGroup = device.createBindGroup({
    layout: bindGroupLayout,
    entries: [
      { binding: 0, resource: { buffer: uniformBuffer } },
      { binding: 1, resource: textureViews['src'] },
      { binding: 2, resource: samplers['src'] },
    ],
  });

  const rebuildBindGroup = () => {
    bindGroup = device.createBindGroup({
      layout: bindGroupLayout,
      entries: [
        { binding: 0, resource: { buffer: uniformBuffer } },
        { binding: 1, resource: textureViews['src'] },
        { binding: 2, resource: samplers['src'] },
      ],
    });
  };

  const handles: MathOpMaterialHandles = {
    pipeline,
    get bindGroup() { return bindGroup; },
    setTexture: (name, texture) => {
      textureViews[name] = texture;
      rebuildBindGroup();
    },
    setUniforms: (updates) => {
      currentUniforms = { ...currentUniforms, ...updates };
      packMathOpUniforms(uniformFloats, uniformInts, uniformUints, 0, currentUniforms);
      device.queue.writeBuffer(uniformBuffer, 0, uniformData);
    },
  };

  return handles;
}

export class MathOpEffect extends CustomShaderEffect<MathOpUniforms, MathOpInputs> {
  override effectName = 'MathOp';

  constructor(device: GPUDevice, inputs: MathOpInputs, width = 1280, height = 720, format: GPUTextureFormat = 'rgba16float', clearColor: GPUColor = { r: 0, g: 0, b: 0, a: 1 }, sampleMode: 'nearest' | 'linear' = 'linear') {
    super(device, inputs, {
      factory: (deviceRef, formatRef, options) => createMathOpMaterial(deviceRef, formatRef, { ...options, sampleMode }),
      textureInputKeys: ['src'],
      textureBindingKeys: MathOpTextureNames,
      passTextureSources: MathOpPassTextureSources,
      passCount: 1,
      primaryTextureKey: 'src',
      width,
      height,
      format,
      clearColor,
      uniformMeta: MathOpUniformMeta,
    });
  }

  override setUniforms(uniforms: { mult?: Dynamic<number> }): void {
    const record: ShaderUniforms = {};
    if (uniforms.mult !== undefined) {
      record['mult'] = uniforms.mult;
    }
    super.setUniforms(record);
  }
}

