import type { AbletonClipRawData } from "@avtools/music-types";
// Extracted from sonar_sketch/piano_melodies Project/freeze_loop_setup_sonar.als.
export const melodyNames = ["dscale5", "dscale7", "d7mel"] as const;
export type MelodyName = typeof melodyNames[number];
export const sources: Record<MelodyName, AbletonClipRawData> = {
  "dscale7": {
    "name": "dscale7",
    "duration": 4.0,
    "notes": [
      {
        "pitch": 62,
        "position": 0.0,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 63,
        "position": 0.5,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 66,
        "position": 1.0,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 68,
        "position": 1.5,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 69,
        "position": 2.0,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 71,
        "position": 2.5,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 73,
        "position": 3.0,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 74,
        "position": 3.5,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
    ],
  },
  "dscale5": {
    "name": "dscale5",
    "duration": 3.0,
    "notes": [
      {
        "pitch": 62,
        "position": 0.0,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 66,
        "position": 0.5,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 68,
        "position": 1.0,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 71,
        "position": 1.5,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 73,
        "position": 2.0,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 74,
        "position": 2.5,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
    ],
  },
  "d7mel": {
    "name": "d7mel",
    "duration": 16.0,
    "notes": [
      {
        "pitch": 61,
        "position": 0.0,
        "duration": 0.5,
        "velocity": 100.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 62,
        "position": 0.5,
        "duration": 1.0,
        "velocity": 101.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 62,
        "position": 1.5,
        "duration": 0.5,
        "velocity": 101.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 71,
        "position": 2.0,
        "duration": 1.0,
        "velocity": 101.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 68,
        "position": 3.0,
        "duration": 1.0,
        "velocity": 99.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 73,
        "position": 4.0,
        "duration": 0.5,
        "velocity": 98.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 71,
        "position": 4.5,
        "duration": 0.5,
        "velocity": 97.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 73,
        "position": 5.0,
        "duration": 1.0,
        "velocity": 97.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 71,
        "position": 6.0,
        "duration": 1.0,
        "velocity": 101.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 68,
        "position": 7.0,
        "duration": 1.0,
        "velocity": 99.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 69,
        "position": 8.0,
        "duration": 0.5,
        "velocity": 97.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 68,
        "position": 8.5,
        "duration": 0.5,
        "velocity": 97.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 69,
        "position": 9.0,
        "duration": 0.5,
        "velocity": 97.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 66,
        "position": 9.5,
        "duration": 0.5,
        "velocity": 97.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 62,
        "position": 10.0,
        "duration": 0.5,
        "velocity": 97.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 61,
        "position": 10.5,
        "duration": 0.5,
        "velocity": 97.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 62,
        "position": 11.0,
        "duration": 1.0,
        "velocity": 97.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 69,
        "position": 12.0,
        "duration": 0.5,
        "velocity": 97.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 68,
        "position": 12.5,
        "duration": 0.5,
        "velocity": 97.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 66,
        "position": 13.0,
        "duration": 0.5,
        "velocity": 97.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 62,
        "position": 13.5,
        "duration": 0.5,
        "velocity": 95.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
      {
        "pitch": 61,
        "position": 14.0,
        "duration": 2.0,
        "velocity": 95.0,
        "offVelocity": 64.0,
        "probability": 1.0,
        "isEnabled": true,
      },
    ],
  },
};

export default async function describe(
  ctx: import("@avtools/core-timing").TimeContext,
) {
  await ctx.waitSec(0.01);
}
