// Generated by tools/gen_shaders.ts from lib/radiance-cascades/shaders/*.wgsl.
// DO NOT EDIT; edit the .wgsl files and regenerate.

/** bounce.wgsl, includes expanded. */
export const BOUNCE_WGSL =
  `// Effective emission for the next frame: the scene's emission plus, inside an
// outline, the light that reached the outline last frame times its albedo.
// Incoming light is the hemispherical irradiance just outside the surface
// (cascade 0's stored directions, cosine-weighted against the outline
// normal), and a diffuse 2D surface re-emits albedo * E / 2.

// ---- fullscreen_vertex.wgsl ----
@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}


struct BounceUniforms {
  probeCount: vec2f,
  probeSpacing: f32,
  storedDirs: f32,
  tileCols: f32,
  rayCount: f32,
  strength: f32,
  offset: f32,
};
@group(0) @binding(0) var<uniform> u: BounceUniforms;
@group(0) @binding(1) var emissionTex: texture_2d<f32>;
@group(0) @binding(2) var albedoTex: texture_2d<f32>;
@group(0) @binding(3) var distanceTex: texture_2d<f32>;
@group(0) @binding(4) var radianceTex: texture_2d<f32>;

const TAU_F: f32 = 6.283185307179586;

fn texelOf(probe: vec2i, stored: i32) -> vec2i {
  let cols = i32(u.tileCols);
  return vec2i(stored % cols, stored / cols) * vec2i(u.probeCount) + probe;
}

@fragment
fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4f {
  let texel = vec2i(floor(pos.xy));
  let e = textureLoad(emissionTex, texel, 0);
  if (u.strength <= 0.0 || e.a < 0.5) {
    return e;
  }
  let dims = vec2i(textureDimensions(distanceTex));
  let d = textureLoad(distanceTex, texel, 0).r;
  let dx = textureLoad(distanceTex, clamp(texel + vec2i(1, 0), vec2i(0), dims - 1), 0).r
    - textureLoad(distanceTex, clamp(texel - vec2i(1, 0), vec2i(0), dims - 1), 0).r;
  let dy = textureLoad(distanceTex, clamp(texel + vec2i(0, 1), vec2i(0), dims - 1), 0).r
    - textureLoad(distanceTex, clamp(texel - vec2i(0, 1), vec2i(0), dims - 1), 0).r;
  var n = vec2f(dx, dy);
  let nl = length(n);
  let hasNormal = nl > 1e-4;
  n = select(vec2f(0.0), n / max(nl, 1e-4), hasNormal);
  let samplePos = pos.xy + n * (max(-d, 0.0) + u.offset);

  let upos = samplePos / u.probeSpacing - 0.5;
  let base = vec2i(floor(upos));
  let f = fract(upos);
  let weights = vec4f((1.0 - f.x) * (1.0 - f.y), f.x * (1.0 - f.y), (1.0 - f.x) * f.y, f.x * f.y);
  let dirs = i32(u.storedDirs);
  let group = u.rayCount / u.storedDirs;
  var irradiance = vec3f(0.0);
  for (var k = 0; k < dirs; k++) {
    var weight = 2.0 / f32(dirs);
    if (dirs > 1 && hasNormal) {
      let a = TAU_F * (f32(k) * group + group * 0.5) / u.rayCount;
      weight = max(0.0, dot(vec2f(cos(a), sin(a)), n)) * TAU_F / f32(dirs);
    }
    var L = vec3f(0.0);
    for (var c = 0; c < 4; c++) {
      let q = clamp(base + vec2i(c % 2, c / 2), vec2i(0), vec2i(u.probeCount) - vec2i(1));
      L += weights[c] * textureLoad(radianceTex, texelOf(q, k), 0).rgb;
    }
    irradiance += L * weight;
  }
  let albedo = textureLoad(albedoTex, texel, 0).rgb;
  return vec4f(e.rgb + u.strength * albedo * irradiance * 0.5, e.a);
}
`;

/** cascade.wgsl, includes expanded. */
export const CASCADE_WGSL =
  `// One cascade level. Direction-major layout: the texture is a grid of
// tiles, tile k holding the whole probe grid for stored direction k.
// Outputs: merged radiance, merged transmittance, and this level's own
// interval radiance before merging (for debugging).

// ---- fullscreen_vertex.wgsl ----
@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}


struct CascadeUniforms {
  sky: vec4f,
  sceneSize: vec2f,
  probeCount: vec2f,
  upperProbeCount: vec2f,
  probeSpacing: f32,
  upperSpacing: f32,
  rayCount: f32,
  storedDirs: f32,
  upperRayCount: f32,
  upperStoredDirs: f32,
  tileCols: f32,
  upperTileCols: f32,
  intervalStart: f32,
  intervalEnd: f32,
  branching: f32,
  isTop: f32,
  mergeMode: f32,
  preAverage: f32,
  useDistanceField: f32,
  stepSize: f32,
  intervalOverlap: f32,
  maxSteps: f32,
};
@group(0) @binding(0) var<uniform> u: CascadeUniforms;
@group(0) @binding(1) var emissionTex: texture_2d<f32>;
@group(0) @binding(2) var transmittanceTex: texture_2d<f32>;
@group(0) @binding(3) var distanceTex: texture_2d<f32>;
@group(0) @binding(4) var upperRadiance: texture_2d<f32>;
@group(0) @binding(5) var upperTransmittance: texture_2d<f32>;

// ---- march.wgsl ----
// Shared ray march. The including shader supplies the scene accessors
//   fn sceneDistance(texel: vec2i) -> f32      signed distance to the nearest outline
//   fn sceneMedium(texel: vec2i) -> Medium     emission and transmittance
// (the fragment programs read the scene textures directly; the compute
// cascade reads a workgroup-memory patch when the ray stays inside it) and
// \`marchParams()\`. Sphere-traces the distance field between outlines and
// integrates emission/transmittance per pixel of travel inside them. The
// emission of a step is E * (1 - tau^ds) / (1 - tau): the full E at an opaque
// hit whatever the step, E * ds through clear media.

struct MarchParams {
  sceneSize: vec2f,
  useDistanceField: bool,
  stepSize: f32,
  maxSteps: i32,
};
struct Hit {
  L: vec3f,
  T: vec3f,
};
struct Medium {
  E: vec3f,
  tau: vec3f,
};

fn inBounds(p: vec2f, size: vec2f) -> bool {
  return all(p >= vec2f(0.0)) && all(p < size);
}

// \`originDistance\` is the distance field at \`origin\` when the caller has it
// (every ray of a probe starts at the same point), or a negative number.
fn march(origin: vec2f, to: vec2f, mp: MarchParams, originDistance: f32) -> Hit {
  var L = vec3f(0.0);
  var T = vec3f(1.0);
  let delta = to - origin;
  let len = length(delta);
  if (len <= 0.0) {
    return Hit(L, T);
  }
  let dir = delta / len;
  var t = 0.0;
  // The first step's distance is known when the caller loaded it.
  if (mp.useDistanceField && originDistance > 0.5 && inBounds(origin, mp.sceneSize)) {
    t = originDistance;
  }
  for (var i = 0; i < mp.maxSteps; i++) {
    if (t >= len) { break; }
    let p = origin + dir * t;
    if (!inBounds(p, mp.sceneSize)) { break; }
    let texel = vec2i(floor(p));
    if (mp.useDistanceField) {
      let d = sceneDistance(texel);
      if (d > 0.5) {
        t += max(d, 0.5);
        continue;
      }
    }
    let ds = min(mp.stepSize, len - t);
    let m = sceneMedium(texel);
    let tau = clamp(m.tau, vec3f(0.0), vec3f(1.0));
    if (ds == 1.0) {
      // A whole pixel: tau^1 is tau and the emission factor is exactly 1,
      // for clear and absorbing media alike.
      L += T * m.E;
      T *= tau;
    } else {
      let tauDs = pow(tau, vec3f(ds));
      let clear = tau > vec3f(0.999);
      let emitFactor = select((vec3f(1.0) - tauDs) / max(vec3f(1.0) - tau, vec3f(1e-4)), vec3f(ds), clear);
      L += T * m.E * emitFactor;
      T *= tauDs;
    }
    if (max(T.r, max(T.g, T.b)) < 0.002) {
      T = vec3f(0.0);
      break;
    }
    t += ds;
  }
  return Hit(L, T);
}


fn sceneDistance(texel: vec2i) -> f32 {
  return textureLoad(distanceTex, texel, 0).r;
}

fn sceneMedium(texel: vec2i) -> Medium {
  return Medium(
    textureLoad(emissionTex, texel, 0).rgb,
    textureLoad(transmittanceTex, texel, 0).rgb,
  );
}

fn marchParams() -> MarchParams {
  return MarchParams(u.sceneSize, u.useDistanceField > 0.5, u.stepSize, i32(u.maxSteps));
}

/// The distance field where a probe's rays start, shared by all of them.
fn startDistanceAt(start: vec2f) -> f32 {
  if (u.useDistanceField < 0.5 || !inBounds(start, u.sceneSize)) {
    return -1.0;
  }
  return sceneDistance(vec2i(floor(start)));
}

const TAU_F: f32 = 6.283185307179586;

fn dirOf(index: f32, count: f32) -> vec2f {
  let a = TAU_F * (index + 0.5) / count;
  return vec2f(cos(a), sin(a));
}

fn upperTexel(probe: vec2i, stored: i32) -> vec2i {
  let cols = i32(u.upperTileCols);
  let tile = vec2i(stored % cols, stored / cols);
  return tile * vec2i(u.upperProbeCount) + probe;
}

fn upperSample(probe: vec2i, stored: i32) -> Hit {
  let texel = upperTexel(probe, stored);
  return Hit(
    textureLoad(upperRadiance, texel, 0).rgb,
    textureLoad(upperTransmittance, texel, 0).rgb,
  );
}

fn upperProbe(base: vec2i, corner: i32) -> vec2i {
  return clamp(base + vec2i(corner % 2, corner / 2), vec2i(0), vec2i(u.upperProbeCount) - vec2i(1));
}

struct Merged {
  L: vec3f,
  T: vec3f,
  raw: vec3f,
};

// \`start\` is where this probe's interval begins for direction d: along d
// itself, or, when pre-averaging, along the stored (parent) direction so the
// level below's bilinear-fix rays end exactly where these begin (Yaazarai's
// fork).
fn castMerged(center: vec2f, d: i32, start: vec2f, startDistance: f32) -> Merged {
  let mp = marchParams();
  let w = dirOf(f32(d), u.rayCount);
  let t0 = u.intervalStart;
  let t1 = u.intervalEnd;
  let overlapEnd = center + w * (t0 + (t1 - t0) * u.intervalOverlap);
  if (u.isTop > 0.5) {
    let hit = march(start, overlapEnd, mp, startDistance);
    return Merged(hit.L + hit.T * u.sky.rgb, hit.T, hit.L);
  }
  let upos = center / u.upperSpacing - 0.5;
  let base = vec2i(floor(upos));
  let f = fract(upos);
  let weights = vec4f((1.0 - f.x) * (1.0 - f.y), f.x * (1.0 - f.y), (1.0 - f.x) * f.y, f.x * f.y);
  let upperPerDir = u.upperStoredDirs >= u.upperRayCount - 0.5;
  let B = i32(u.branching);
  let childCount = select(1, B, upperPerDir);
  let mode = i32(u.mergeMode);

  if (mode == 1) {
    // Bilinear fix: one ray per upper probe, from this interval's start to
    // the point where that probe's child interval starts, merged with that
    // probe alone; the four merged results are then bilinearly weighted.
    // Children outer, corners inner: a child direction is computed once and
    // the weighted sum is the same in either order.
    var L = vec3f(0.0);
    var T = vec3f(0.0);
    var raw = vec3f(0.0);
    for (var k = 0; k < childCount; k++) {
      let stored = select(d, d * B + k, upperPerDir);
      let wc = select(w, dirOf(f32(d * B + k), u.upperRayCount), upperPerDir);
      let end = wc * t1;
      for (var c = 0; c < 4; c++) {
        let q = upperProbe(base, c);
        let qCenter = (vec2f(q) + 0.5) * u.upperSpacing;
        let hit = march(start, qCenter + end, mp, startDistance);
        let up = upperSample(q, stored);
        let scale = weights[c] / f32(childCount);
        L += (hit.L + hit.T * up.L) * scale;
        T += hit.T * up.T * scale;
        raw += hit.L * scale;
      }
    }
    return Merged(L, T, raw);
  }

  let hit = march(start, overlapEnd, mp, startDistance);
  var upL = vec3f(0.0);
  var upT = vec3f(0.0);
  for (var c = 0; c < 4; c++) {
    let q = upperProbe(base, c);
    if (mode == 2) {
      // Parallax fix (Sannikov's MERGE_FIX 4): seen from the upper probe,
      // this ray's end point lies off the ray's own direction by a parallax
      // angle, so look the upper probe up in that direction, interpolating
      // its two nearest stored directions. When the upper level stores one
      // texel per ray, shift the whole child cone by the angle rather than
      // collapsing it to one direction, so the cone average survives when
      // cascade 0 has few, wide rays.
      let qCenter = (vec2f(q) + 0.5) * u.upperSpacing;
      let v = overlapEnd - qCenter;
      let nominal = TAU_F * (f32(d) + 0.5) / u.rayCount;
      var shift = atan2(v.y, v.x) - nominal;
      shift = shift - floor((shift + 3.14159265) / TAU_F) * TAU_F;
      let stored = u.upperStoredDirs;
      let shiftIndex = shift / TAU_F * stored;
      var Lc = vec3f(0.0);
      var Tc = vec3f(0.0);
      for (var k = 0; k < childCount; k++) {
        var idx = f32(select(d, d * B + k, upperPerDir)) + shiftIndex;
        idx = idx - floor(idx / stored) * stored;
        let i0 = i32(floor(idx)) % i32(stored);
        let i1 = (i0 + 1) % i32(stored);
        let fr = fract(idx);
        let s0 = upperSample(q, i0);
        let s1 = upperSample(q, i1);
        Lc += mix(s0.L, s1.L, fr);
        Tc += mix(s0.T, s1.T, fr);
      }
      upL += weights[c] * Lc / f32(childCount);
      upT += weights[c] * Tc / f32(childCount);
    } else {
      var Lc = vec3f(0.0);
      var Tc = vec3f(0.0);
      for (var k = 0; k < childCount; k++) {
        let s = upperSample(q, select(d, d * B + k, upperPerDir));
        Lc += s.L;
        Tc += s.T;
      }
      upL += weights[c] * Lc / f32(childCount);
      upT += weights[c] * Tc / f32(childCount);
    }
  }
  return Merged(hit.L + hit.T * upL, hit.T * upT, hit.L);
}

struct Out {
  @location(0) radiance: vec4f,
  @location(1) transmittance: vec4f,
  @location(2) raw: vec4f,
};

/// Without the raw debug target (the pipeline the renderer uses unless the
/// debug views are requested).
struct OutMerged {
  @location(0) radiance: vec4f,
  @location(1) transmittance: vec4f,
};

@fragment
fn fsMerged(@builtin(position) pos: vec4f) -> OutMerged {
  let out = shade(pos);
  return OutMerged(out.radiance, out.transmittance);
}

@fragment
fn fs(@builtin(position) pos: vec4f) -> Out {
  return shade(pos);
}

fn shade(pos: vec4f) -> Out {
  let texel = vec2i(floor(pos.xy));
  let probes = vec2i(u.probeCount);
  let tile = texel / probes;
  let probe = texel - tile * probes;
  let stored = tile.y * i32(u.tileCols) + tile.x;
  var out: Out;
  if (stored >= i32(u.storedDirs)) {
    out.radiance = vec4f(0.0);
    out.transmittance = vec4f(0.0);
    out.raw = vec4f(0.0);
    return out;
  }
  let center = (vec2f(probe) + 0.5) * u.probeSpacing;
  let group = select(1, i32(u.branching), u.preAverage > 0.5);
  let startDir = select(
    dirOf(f32(stored), u.rayCount),
    dirOf(f32(stored), u.storedDirs),
    u.preAverage > 0.5,
  );
  let start = center + startDir * u.intervalStart;
  let startDistance = startDistanceAt(start);
  var L = vec3f(0.0);
  var T = vec3f(0.0);
  var raw = vec3f(0.0);
  for (var j = 0; j < group; j++) {
    let m = castMerged(center, stored * group + j, start, startDistance);
    L += m.L;
    T += m.T;
    raw += m.raw;
  }
  let inv = 1.0 / f32(group);
  out.radiance = vec4f(L * inv, 1.0);
  out.transmittance = vec4f(T * inv, 1.0);
  out.raw = vec4f(raw * inv, 1.0);
  return out;
}
`;

/** compute_bounce.wgsl, includes expanded. */
export const COMPUTE_BOUNCE_WGSL =
  `// Effective emission for the next frame (see bounce.wgsl for the model). The
// compute cascade never stores cascade 0, so the directional radiance near
// outlines comes from the band buffer cascade 0 filled last frame: \`slotMap\`
// maps a probe to its band slot. A probe outside the band (or dropped when the
// band overflowed) contributes its irradiance as if it were uniform over the
// hemisphere, the same as the fragment pass does without a normal.

override TILE: u32 = 16u;

struct BounceUniforms {
  probeCount: vec2u,
  probeSpacing: f32,
  storedDirs: u32,
  rayCount: u32,
  strength: f32,
  offset: f32,
  /// 1: cascade 0 is stored (non-fused); read \`store\` instead of the band.
  fromStore: u32,
};
@group(0) @binding(0) var<uniform> u: BounceUniforms;
@group(0) @binding(1) var emissionTex: texture_2d<f32>;
@group(0) @binding(2) var albedoTex: texture_2d<f32>;
@group(0) @binding(3) var distanceTex: texture_2d<f32>;
@group(0) @binding(4) var<storage, read> slotMap: array<u32>;
@group(0) @binding(5) var<storage, read> band: array<u32>;
@group(0) @binding(6) var probeIrradiance: texture_2d<f32>;
@group(0) @binding(7) var effectiveOut: texture_storage_2d<rgba16float, write>;
@group(0) @binding(8) var<storage, read> store: array<u32>;

const TAU_F: f32 = 6.283185307179586;

fn bandRadiance(slot: u32, k: u32) -> vec3f {
  let i = ((slot - 1u) * u.storedDirs + k) * 2u;
  return vec3f(unpack2x16float(band[i]), unpack2x16float(band[i + 1u]).x);
}

fn storeRadiance(probe: u32, k: u32) -> vec3f {
  let i = (k * u.probeCount.x * u.probeCount.y + probe) * 3u;
  return vec3f(unpack2x16float(store[i]), unpack2x16float(store[i + 1u]).x);
}

@compute @workgroup_size(TILE, TILE, 1)
fn main(@builtin(global_invocation_id) gid: vec3u) {
  let dims = vec2i(textureDimensions(distanceTex));
  if (any(vec2i(gid.xy) >= dims)) {
    return;
  }
  let texel = vec2i(gid.xy);
  let e = textureLoad(emissionTex, texel, 0);
  if (u.strength <= 0.0 || e.a < 0.5) {
    textureStore(effectiveOut, texel, e);
    return;
  }
  let pos = vec2f(texel) + 0.5;
  let d = textureLoad(distanceTex, texel, 0).r;
  let dx = textureLoad(distanceTex, clamp(texel + vec2i(1, 0), vec2i(0), dims - 1), 0).r
    - textureLoad(distanceTex, clamp(texel - vec2i(1, 0), vec2i(0), dims - 1), 0).r;
  let dy = textureLoad(distanceTex, clamp(texel + vec2i(0, 1), vec2i(0), dims - 1), 0).r
    - textureLoad(distanceTex, clamp(texel - vec2i(0, 1), vec2i(0), dims - 1), 0).r;
  var n = vec2f(dx, dy);
  let nl = length(n);
  let hasNormal = nl > 1e-4;
  n = select(vec2f(0.0), n / max(nl, 1e-4), hasNormal);
  let samplePos = pos + n * (max(-d, 0.0) + u.offset);

  let upos = samplePos / u.probeSpacing - 0.5;
  let base = vec2i(floor(upos));
  let f = fract(upos);
  let weights = vec4f((1.0 - f.x) * (1.0 - f.y), f.x * (1.0 - f.y), (1.0 - f.x) * f.y, f.x * f.y);
  let dirs = u.storedDirs;
  let group = f32(u.rayCount) / f32(dirs);
  var slots = vec4u(0u);
  var probes = vec4u(0u);
  var means = array<vec3f, 4>();
  for (var c = 0; c < 4; c++) {
    let q = clamp(base + vec2i(c % 2, c / 2), vec2i(0), vec2i(u.probeCount) - vec2i(1));
    probes[c] = u32(q.y) * u.probeCount.x + u32(q.x);
    if (u.fromStore == 0u) {
      slots[c] = slotMap[probes[c]];
      means[c] = textureLoad(probeIrradiance, q, 0).rgb;
    }
  }
  var irradiance = vec3f(0.0);
  for (var k = 0u; k < dirs; k++) {
    var weight = 2.0 / f32(dirs);
    if (dirs > 1u && hasNormal) {
      let a = TAU_F * (f32(k) * group + group * 0.5) / f32(u.rayCount);
      weight = max(0.0, dot(vec2f(cos(a), sin(a)), n)) * TAU_F / f32(dirs);
    }
    var L = vec3f(0.0);
    for (var c = 0; c < 4; c++) {
      if (u.fromStore != 0u) {
        L += weights[c] * storeRadiance(probes[c], k);
      } else {
        let slot = slots[c];
        L += weights[c] * select(means[c], bandRadiance(slot, k), slot != 0u);
      }
    }
    irradiance += L * weight;
  }
  let albedo = textureLoad(albedoTex, texel, 0).rgb;
  textureStore(effectiveOut, texel, vec4f(e.rgb + u.strength * albedo * irradiance * 0.5, e.a));
}
`;

/** compute_cascade.wgsl, includes expanded. */
export const COMPUTE_CASCADE_WGSL =
  `// One cascade level as a compute pass. A lane is one (probe, stored direction);
// a workgroup is a TX x TY tile of probes times DW consecutive stored
// directions, laid out 1D with the probe fastest, so a SIMD group holds
// neighbouring probes marching the same direction (as the fragment tiling
// does) rather than one probe's divergent directions. Levels are stored in
// storage buffers, direction-major (dir * probes + probe), each entry three
// u32 of packed f16: radiance rgb and transmittance rgb. What the fragment
// version cannot do:
//
// - USE_PATCH: the scene texels every ray of the tile can touch (tile extent
//   plus a halo) are loaded into workgroup memory once and marched there.
//   Worth it where many short rays share a small patch (cascade 0 with the
//   bilinear fix); the planner decides per level.
// - USE_FOOT: the upper-level probes and directions this tile merges with are
//   staged in workgroup memory once instead of being re-read per lane.
// - REDUCE (cascade 0): a lane is one probe and loops over all of its
//   stored directions, so a SIMD group of neighbouring probes marches one
//   direction at a time (as the fragment tiling does), the direction mean
//   stays in registers and goes straight to the irradiance texture, and
//   cascade 0 is never stored. Probes within \`bandWidth\` of an outline also
//   append their directional radiance to a compact band buffer (atomic slot
//   counter) for the bounce pass. Needs no workgroup memory or barrier.
// Rays are otherwise identical to cascade.wgsl (merge modes, pre-averaging,
// overlap, sky).

override TX: u32 = 16u;
override TY: u32 = 16u;
override DW: u32 = 1u;
override REDUCE: bool = false;
override USE_PATCH: bool = false;
override PATCH_W: u32 = 1u;
override PATCH_H: u32 = 1u;
override USE_FOOT: bool = false;
override FOOT_X: u32 = 1u;
override FOOT_Y: u32 = 1u;
override FOOT_D: u32 = 1u;

struct CascadeUniforms {
  sky: vec4f,
  sceneSize: vec2f,
  probeCount: vec2u,
  upperProbeCount: vec2u,
  probeSpacing: f32,
  upperSpacing: f32,
  rayCount: u32,
  storedDirs: u32,
  upperRayCount: u32,
  upperStoredDirs: u32,
  intervalStart: f32,
  intervalEnd: f32,
  branching: u32,
  isTop: u32,
  mergeMode: u32,
  preAverage: u32,
  useDistanceField: u32,
  stepSize: f32,
  intervalOverlap: f32,
  maxSteps: i32,
  storeDirs: u32,
  storeRaw: u32,
  bandCapacity: u32,
  bandWidth: f32,
  halo: f32,
  pad0: f32,
};
struct Counter {
  n: atomic<u32>,
};
@group(0) @binding(0) var<uniform> u: CascadeUniforms;
@group(0) @binding(1) var emissionTex: texture_2d<f32>;
@group(0) @binding(2) var transmittanceTex: texture_2d<f32>;
@group(0) @binding(3) var distanceTex: texture_2d<f32>;
/// The level above, packed; unused at the top.
@group(0) @binding(4) var<storage, read> upper: array<u32>;
/// This level's store, packed; written when \`storeDirs\` is set.
@group(0) @binding(5) var<storage, read_write> own: array<u32>;
/// This level's own-interval radiance for debugging, two u32 per entry.
@group(0) @binding(6) var<storage, read_write> rawStore: array<u32>;
/// REDUCE only: per-probe irradiance.
@group(0) @binding(7) var irradianceOut: texture_storage_2d<rgba16float, write>;
/// REDUCE only: probe -> band slot + 1, 0 when the probe is not in the band.
@group(0) @binding(8) var<storage, read_write> slotMap: array<u32>;
/// REDUCE only: per band slot, DW radiances of two packed u32.
@group(0) @binding(9) var<storage, read_write> band: array<u32>;
@group(0) @binding(10) var<storage, read_write> bandCounter: Counter;

var<workgroup> scenePatch: array<vec4u, PATCH_W * PATCH_H>;
var<workgroup> footprint: array<u32, FOOT_X * FOOT_Y * FOOT_D * 3u>;

var<private> patchOrigin: vec2i;
var<private> footOrigin: vec2i;
var<private> footDir0: u32;

fn patchWord(texel: vec2i) -> vec4u {
  let l = texel - patchOrigin;
  return scenePatch[u32(l.y) * PATCH_W + u32(l.x)];
}

fn inPatch(texel: vec2i) -> bool {
  let l = texel - patchOrigin;
  return USE_PATCH && all(l >= vec2i(0)) && l.x < i32(PATCH_W) && l.y < i32(PATCH_H);
}

// ---- march.wgsl ----
// Shared ray march. The including shader supplies the scene accessors
//   fn sceneDistance(texel: vec2i) -> f32      signed distance to the nearest outline
//   fn sceneMedium(texel: vec2i) -> Medium     emission and transmittance
// (the fragment programs read the scene textures directly; the compute
// cascade reads a workgroup-memory patch when the ray stays inside it) and
// \`marchParams()\`. Sphere-traces the distance field between outlines and
// integrates emission/transmittance per pixel of travel inside them. The
// emission of a step is E * (1 - tau^ds) / (1 - tau): the full E at an opaque
// hit whatever the step, E * ds through clear media.

struct MarchParams {
  sceneSize: vec2f,
  useDistanceField: bool,
  stepSize: f32,
  maxSteps: i32,
};
struct Hit {
  L: vec3f,
  T: vec3f,
};
struct Medium {
  E: vec3f,
  tau: vec3f,
};

fn inBounds(p: vec2f, size: vec2f) -> bool {
  return all(p >= vec2f(0.0)) && all(p < size);
}

// \`originDistance\` is the distance field at \`origin\` when the caller has it
// (every ray of a probe starts at the same point), or a negative number.
fn march(origin: vec2f, to: vec2f, mp: MarchParams, originDistance: f32) -> Hit {
  var L = vec3f(0.0);
  var T = vec3f(1.0);
  let delta = to - origin;
  let len = length(delta);
  if (len <= 0.0) {
    return Hit(L, T);
  }
  let dir = delta / len;
  var t = 0.0;
  // The first step's distance is known when the caller loaded it.
  if (mp.useDistanceField && originDistance > 0.5 && inBounds(origin, mp.sceneSize)) {
    t = originDistance;
  }
  for (var i = 0; i < mp.maxSteps; i++) {
    if (t >= len) { break; }
    let p = origin + dir * t;
    if (!inBounds(p, mp.sceneSize)) { break; }
    let texel = vec2i(floor(p));
    if (mp.useDistanceField) {
      let d = sceneDistance(texel);
      if (d > 0.5) {
        t += max(d, 0.5);
        continue;
      }
    }
    let ds = min(mp.stepSize, len - t);
    let m = sceneMedium(texel);
    let tau = clamp(m.tau, vec3f(0.0), vec3f(1.0));
    if (ds == 1.0) {
      // A whole pixel: tau^1 is tau and the emission factor is exactly 1,
      // for clear and absorbing media alike.
      L += T * m.E;
      T *= tau;
    } else {
      let tauDs = pow(tau, vec3f(ds));
      let clear = tau > vec3f(0.999);
      let emitFactor = select((vec3f(1.0) - tauDs) / max(vec3f(1.0) - tau, vec3f(1e-4)), vec3f(ds), clear);
      L += T * m.E * emitFactor;
      T *= tauDs;
    }
    if (max(T.r, max(T.g, T.b)) < 0.002) {
      T = vec3f(0.0);
      break;
    }
    t += ds;
  }
  return Hit(L, T);
}


fn sceneDistance(texel: vec2i) -> f32 {
  if (inPatch(texel)) {
    return bitcast<f32>(patchWord(texel).w);
  }
  return textureLoad(distanceTex, texel, 0).r;
}

fn sceneMedium(texel: vec2i) -> Medium {
  if (inPatch(texel)) {
    let w = patchWord(texel);
    let a = unpack2x16float(w.x);
    let b = unpack2x16float(w.y);
    let c = unpack2x16float(w.z);
    return Medium(vec3f(a, b.x), vec3f(b.y, c));
  }
  return Medium(
    textureLoad(emissionTex, texel, 0).rgb,
    textureLoad(transmittanceTex, texel, 0).rgb,
  );
}

fn marchParams() -> MarchParams {
  return MarchParams(u.sceneSize, u.useDistanceField != 0u, u.stepSize, u.maxSteps);
}

/// The distance field where a probe's rays start, shared by all of them.
fn startDistanceAt(start: vec2f) -> f32 {
  if (u.useDistanceField == 0u || !inBounds(start, u.sceneSize)) {
    return -1.0;
  }
  return sceneDistance(vec2i(floor(start)));
}

const TAU_F: f32 = 6.283185307179586;

fn dirOf(index: f32, count: f32) -> vec2f {
  let a = TAU_F * (index + 0.5) / count;
  return vec2f(cos(a), sin(a));
}

fn unpackLT(x: u32, y: u32, z: u32) -> Hit {
  let a = unpack2x16float(x);
  let b = unpack2x16float(y);
  let c = unpack2x16float(z);
  return Hit(vec3f(a, b.x), vec3f(b.y, c));
}

fn upperIndex(probe: vec2i, stored: u32) -> u32 {
  let probes = u.upperProbeCount.x * u.upperProbeCount.y;
  return (stored * probes + u32(probe.y) * u.upperProbeCount.x + u32(probe.x)) * 3u;
}

fn upperSample(probe: vec2i, stored: u32) -> Hit {
  if (USE_FOOT) {
    let l = probe - footOrigin;
    let dd = i32(stored) - i32(footDir0);
    if (all(l >= vec2i(0)) && l.x < i32(FOOT_X) && l.y < i32(FOOT_Y) && dd >= 0 && dd < i32(FOOT_D)) {
      let i = ((u32(l.y) * FOOT_X + u32(l.x)) * FOOT_D + u32(dd)) * 3u;
      return unpackLT(footprint[i], footprint[i + 1u], footprint[i + 2u]);
    }
  }
  let i = upperIndex(probe, stored);
  return unpackLT(upper[i], upper[i + 1u], upper[i + 2u]);
}

fn upperProbe(base: vec2i, corner: i32) -> vec2i {
  return clamp(base + vec2i(corner % 2, corner / 2), vec2i(0), vec2i(u.upperProbeCount) - vec2i(1));
}

struct Merged {
  L: vec3f,
  T: vec3f,
  raw: vec3f,
};

// Identical to cascade.wgsl's castMerged; see there for the merge modes.
fn castMerged(center: vec2f, d: i32, start: vec2f, startDistance: f32) -> Merged {
  let mp = marchParams();
  let rayCount = f32(u.rayCount);
  let w = dirOf(f32(d), rayCount);
  let t0 = u.intervalStart;
  let t1 = u.intervalEnd;
  let overlapEnd = center + w * (t0 + (t1 - t0) * u.intervalOverlap);
  if (u.isTop != 0u) {
    let hit = march(start, overlapEnd, mp, startDistance);
    return Merged(hit.L + hit.T * u.sky.rgb, hit.T, hit.L);
  }
  let upos = center / u.upperSpacing - 0.5;
  let base = vec2i(floor(upos));
  let f = fract(upos);
  let weights = vec4f((1.0 - f.x) * (1.0 - f.y), f.x * (1.0 - f.y), (1.0 - f.x) * f.y, f.x * f.y);
  let upperPerDir = u.upperStoredDirs >= u.upperRayCount;
  let B = i32(u.branching);
  let childCount = select(1, B, upperPerDir);
  let upperRayCount = f32(u.upperRayCount);

  if (u.mergeMode == 1u) {
    // Children outer, corners inner: a child direction is computed once and
    // the weighted sum is the same in either order.
    var L = vec3f(0.0);
    var T = vec3f(0.0);
    var raw = vec3f(0.0);
    for (var k = 0; k < childCount; k++) {
      let stored = select(d, d * B + k, upperPerDir);
      let wc = select(w, dirOf(f32(d * B + k), upperRayCount), upperPerDir);
      let end = wc * t1;
      for (var c = 0; c < 4; c++) {
        let q = upperProbe(base, c);
        let qCenter = (vec2f(q) + 0.5) * u.upperSpacing;
        let hit = march(start, qCenter + end, mp, startDistance);
        let up = upperSample(q, u32(stored));
        let scale = weights[c] / f32(childCount);
        L += (hit.L + hit.T * up.L) * scale;
        T += hit.T * up.T * scale;
        raw += hit.L * scale;
      }
    }
    return Merged(L, T, raw);
  }

  let hit = march(start, overlapEnd, mp, startDistance);
  var upL = vec3f(0.0);
  var upT = vec3f(0.0);
  for (var c = 0; c < 4; c++) {
    let q = upperProbe(base, c);
    if (u.mergeMode == 2u) {
      let qCenter = (vec2f(q) + 0.5) * u.upperSpacing;
      let v = overlapEnd - qCenter;
      let nominal = TAU_F * (f32(d) + 0.5) / rayCount;
      var shift = atan2(v.y, v.x) - nominal;
      shift = shift - floor((shift + 3.14159265) / TAU_F) * TAU_F;
      let stored = f32(u.upperStoredDirs);
      let shiftIndex = shift / TAU_F * stored;
      var Lc = vec3f(0.0);
      var Tc = vec3f(0.0);
      for (var k = 0; k < childCount; k++) {
        var idx = f32(select(d, d * B + k, upperPerDir)) + shiftIndex;
        idx = idx - floor(idx / stored) * stored;
        let i0 = i32(floor(idx)) % i32(stored);
        let i1 = (i0 + 1) % i32(stored);
        let fr = fract(idx);
        let s0 = upperSample(q, u32(i0));
        let s1 = upperSample(q, u32(i1));
        Lc += mix(s0.L, s1.L, fr);
        Tc += mix(s0.T, s1.T, fr);
      }
      upL += weights[c] * Lc / f32(childCount);
      upT += weights[c] * Tc / f32(childCount);
    } else {
      var Lc = vec3f(0.0);
      var Tc = vec3f(0.0);
      for (var k = 0; k < childCount; k++) {
        let s = upperSample(q, u32(select(d, d * B + k, upperPerDir)));
        Lc += s.L;
        Tc += s.T;
      }
      upL += weights[c] * Lc / f32(childCount);
      upT += weights[c] * Tc / f32(childCount);
    }
  }
  return Merged(hit.L + hit.T * upL, hit.T * upT, hit.L);
}

// One stored direction of a probe: its \`group\` rays merged and averaged.
fn castStored(center: vec2f, stored: u32, group: u32) -> Merged {
  let startDir = select(
    dirOf(f32(stored), f32(u.rayCount)),
    dirOf(f32(stored), f32(u.storedDirs)),
    u.preAverage != 0u,
  );
  let start = center + startDir * u.intervalStart;
  let startDistance = startDistanceAt(start);
  var L = vec3f(0.0);
  var T = vec3f(0.0);
  var raw = vec3f(0.0);
  for (var j = 0u; j < group; j++) {
    let m = castMerged(center, i32(stored * group + j), start, startDistance);
    L += m.L;
    T += m.T;
    raw += m.raw;
  }
  let inv = 1.0 / f32(group);
  return Merged(L * inv, T * inv, raw * inv);
}

fn storeEntry(entry: u32, m: Merged) {
  own[entry * 3u] = pack2x16float(m.L.rg);
  own[entry * 3u + 1u] = pack2x16float(vec2f(m.L.b, m.T.r));
  own[entry * 3u + 2u] = pack2x16float(m.T.gb);
}

@compute @workgroup_size(TX * TY * DW, 1, 1)
fn main(
  @builtin(workgroup_id) wg: vec3u,
  @builtin(local_invocation_index) li: u32,
) {
  let lanes = TX * TY * DW;
  let laneProbe = li % (TX * TY);
  let laneDir = li / (TX * TY);
  let lid = vec2u(laneProbe % TX, laneProbe / TX);
  let tileOrigin = vec2i(wg.xy * vec2u(TX, TY));
  let dir0 = wg.z * DW;
  let sceneDims = vec2i(u.sceneSize);

  // Workgroup memory: the scene patch every ray of this tile stays inside.
  patchOrigin = vec2i(floor(vec2f(tileOrigin) * u.probeSpacing - u.halo));
  if (USE_PATCH) {
    let n = PATCH_W * PATCH_H;
    for (var i = li; i < n; i += lanes) {
      let local = vec2i(i32(i % PATCH_W), i32(i / PATCH_W));
      let texel = clamp(patchOrigin + local, vec2i(0), sceneDims - vec2i(1));
      let E = textureLoad(emissionTex, texel, 0).rgb;
      let tau = textureLoad(transmittanceTex, texel, 0).rgb;
      let d = textureLoad(distanceTex, texel, 0).r;
      scenePatch[i] = vec4u(
        pack2x16float(E.rg),
        pack2x16float(vec2f(E.b, tau.r)),
        pack2x16float(tau.gb),
        bitcast<u32>(d),
      );
    }
  }

  // Workgroup memory: the upper probes and directions this tile merges with.
  // A stored direction s of this level reads upper directions
  // [s * G, (s + 1) * G): its G = group * childCount children.
  let group = select(1u, u.branching, u.preAverage != 0u);
  let upperPerDir = u.upperStoredDirs >= u.upperRayCount;
  let G = group * select(1u, u.branching, upperPerDir);
  footDir0 = select(dir0 * G, 0u, REDUCE);
  footOrigin = clamp(
    vec2i(floor((vec2f(tileOrigin) + 0.5) * u.probeSpacing / u.upperSpacing - 0.5)),
    vec2i(0),
    max(vec2i(0), vec2i(u.upperProbeCount) - vec2i(i32(FOOT_X), i32(FOOT_Y))),
  );
  if (USE_FOOT && u.isTop == 0u) {
    let n = FOOT_X * FOOT_Y * FOOT_D;
    for (var i = li; i < n; i += lanes) {
      let dd = i % FOOT_D;
      let rest = i / FOOT_D;
      let q = footOrigin + vec2i(i32(rest % FOOT_X), i32(rest / FOOT_X));
      let upDir = footDir0 + dd;
      if (all(q < vec2i(u.upperProbeCount)) && upDir < u.upperStoredDirs) {
        let src = upperIndex(q, upDir);
        footprint[i * 3u] = upper[src];
        footprint[i * 3u + 1u] = upper[src + 1u];
        footprint[i * 3u + 2u] = upper[src + 2u];
      }
    }
  }
  workgroupBarrier();

  let probe = tileOrigin + vec2i(lid);
  let live = all(probe < vec2i(u.probeCount));
  let probeIndex = u32(probe.y) * u.probeCount.x + u32(probe.x);
  let probes = u.probeCount.x * u.probeCount.y;
  if (!live) {
    return;
  }
  let center = (vec2f(probe) + 0.5) * u.probeSpacing;

  if (REDUCE) {
    // Band membership first: this lane's probe, all its directions.
    var slot = 0u;
    let d = sceneDistance(clamp(vec2i(floor(center)), vec2i(0), sceneDims - vec2i(1)));
    if (d < u.bandWidth) {
      let claimed = atomicAdd(&bandCounter.n, 1u);
      slot = select(0u, claimed + 1u, claimed < u.bandCapacity);
    }
    slotMap[probeIndex] = slot;
    var sum = vec3f(0.0);
    for (var stored = 0u; stored < u.storedDirs; stored++) {
      let m = castStored(center, stored, group);
      sum += m.L;
      let entry = stored * probes + probeIndex;
      if (u.storeDirs != 0u) {
        storeEntry(entry, m);
      }
      if (u.storeRaw != 0u) {
        rawStore[entry * 2u] = pack2x16float(m.raw.rg);
        rawStore[entry * 2u + 1u] = pack2x16float(vec2f(m.raw.b, 0.0));
      }
      if (slot != 0u) {
        let i = ((slot - 1u) * u.storedDirs + stored) * 2u;
        band[i] = pack2x16float(m.L.rg);
        band[i + 1u] = pack2x16float(vec2f(m.L.b, 0.0));
      }
    }
    textureStore(irradianceOut, probe, vec4f(sum / f32(u.storedDirs), 1.0));
    return;
  }

  let stored = dir0 + laneDir;
  if (stored >= u.storedDirs) {
    return;
  }
  let m = castStored(center, stored, group);
  let entry = stored * probes + probeIndex;
  if (u.storeDirs != 0u) {
    storeEntry(entry, m);
  }
  if (u.storeRaw != 0u) {
    rawStore[entry * 2u] = pack2x16float(m.raw.rg);
    rawStore[entry * 2u + 1u] = pack2x16float(vec2f(m.raw.b, 0.0));
  }
}
`;

/** compute_debug_unpack.wgsl, includes expanded. */
export const COMPUTE_DEBUG_UNPACK_WGSL =
  `// Debug views for the compute backend: unpack a level's store (and raw store)
// into the direction-tiled textures the fragment backend renders directly, so
// the same display pass shows either.

override TILE: u32 = 16u;

struct UnpackUniforms {
  probeCount: vec2u,
  storedDirs: u32,
  tileCols: u32,
};
@group(0) @binding(0) var<uniform> u: UnpackUniforms;
@group(0) @binding(1) var<storage, read> store: array<u32>;
@group(0) @binding(2) var<storage, read> rawStore: array<u32>;
@group(0) @binding(3) var mergedOut: texture_storage_2d<rgba16float, write>;
@group(0) @binding(4) var rawOut: texture_storage_2d<rgba16float, write>;

@compute @workgroup_size(TILE, TILE, 1)
fn main(@builtin(global_invocation_id) gid: vec3u) {
  let dims = vec2i(textureDimensions(mergedOut));
  if (any(vec2i(gid.xy) >= dims)) {
    return;
  }
  let texel = vec2i(gid.xy);
  let probes = vec2i(u.probeCount);
  let tile = texel / probes;
  let probe = texel - tile * probes;
  let stored = u32(tile.y) * u.tileCols + u32(tile.x);
  if (stored >= u.storedDirs) {
    textureStore(mergedOut, texel, vec4f(0.0));
    textureStore(rawOut, texel, vec4f(0.0));
    return;
  }
  let entry = stored * u32(probes.x * probes.y) + u32(probe.y * probes.x + probe.x);
  let a = unpack2x16float(store[entry * 3u]);
  let b = unpack2x16float(store[entry * 3u + 1u]);
  textureStore(mergedOut, texel, vec4f(a, b.x, 1.0));
  let r = unpack2x16float(rawStore[entry * 2u]);
  let s = unpack2x16float(rawStore[entry * 2u + 1u]);
  textureStore(rawOut, texel, vec4f(r, s.x, 1.0));
}
`;

/** compute_gather.wgsl, includes expanded. */
export const COMPUTE_GATHER_WGSL =
  `// Per-pixel irradiance from a stored cascade 0 (the non-fused path): the
// bilinear gather of gather.wgsl over the packed direction store.

override TILE: u32 = 16u;

struct GatherUniforms {
  probeCount: vec2u,
  probeSpacing: f32,
  storedDirs: u32,
};
@group(0) @binding(0) var<uniform> u: GatherUniforms;
@group(0) @binding(1) var<storage, read> store: array<u32>;
@group(0) @binding(2) var irradianceOut: texture_storage_2d<rgba16float, write>;

@compute @workgroup_size(TILE, TILE, 1)
fn main(@builtin(global_invocation_id) gid: vec3u) {
  let dims = vec2i(textureDimensions(irradianceOut));
  if (any(vec2i(gid.xy) >= dims)) {
    return;
  }
  let pos = vec2f(gid.xy) + 0.5;
  let upos = pos / u.probeSpacing - 0.5;
  let base = vec2i(floor(upos));
  let f = fract(upos);
  let weights = vec4f((1.0 - f.x) * (1.0 - f.y), f.x * (1.0 - f.y), (1.0 - f.x) * f.y, f.x * f.y);
  let probes = u.probeCount.x * u.probeCount.y;
  var sum = vec3f(0.0);
  for (var c = 0; c < 4; c++) {
    let q = clamp(base + vec2i(c % 2, c / 2), vec2i(0), vec2i(u.probeCount) - vec2i(1));
    let probe = u32(q.y) * u.probeCount.x + u32(q.x);
    var Lc = vec3f(0.0);
    for (var k = 0u; k < u.storedDirs; k++) {
      let i = (k * probes + probe) * 3u;
      Lc += vec3f(unpack2x16float(store[i]), unpack2x16float(store[i + 1u]).x);
    }
    sum += weights[c] * Lc;
  }
  textureStore(irradianceOut, vec2i(gid.xy), vec4f(sum / f32(u.storedDirs), 1.0));
}
`;

/** compute_scene_bins.wgsl, includes expanded. */
export const COMPUTE_SCENE_BINS_WGSL =
  `// Compute scene rasterizer, pass 1: bin the segments per screen tile so the
// raster pass tests only nearby segments. One workgroup per tile; its lanes
// stride over the segments and claim bin slots with a workgroup atomic. A
// segment joins a tile's bin when its outline can come within \`binRadius\` of
// any pixel of the tile (tile-centre distance minus half the tile diagonal).
// The pass also records, per tile, the distance from the tile centre to the
// nearest outline over ALL segments: pixels whose nearest outline is not in
// the bin take that minus half a diagonal as a conservative lower bound, which
// is all sphere tracing needs.

override TILE: u32 = 16u;
override BIN_CAPACITY: u32 = 128u;
override LANES: u32 = 64u;

struct SceneUniforms {
  size: vec2f,
  segmentCount: u32,
  shapeCount: u32,
  tiles: vec2u,
  binRadius: f32,
  pad: f32,
};
struct Segment {
  a: vec2f,
  b: vec2f,
  shape: u32,
  pad: u32,
};
struct Material {
  emission: vec4f,       // rgb, halfWidth
  transmittance: vec4f,  // rgb, 0
  albedo: vec4f,         // rgb, 0
};
@group(0) @binding(0) var<uniform> u: SceneUniforms;
@group(0) @binding(1) var<storage, read> segments: array<Segment>;
@group(0) @binding(2) var<storage, read> materials: array<Material>;
/// \`tiles.x * tiles.y * BIN_CAPACITY\` segment indices.
@group(0) @binding(3) var<storage, read_write> bins: array<u32>;
/// Per tile: (segments that wanted a slot, bits of the tile-centre distance).
@group(0) @binding(4) var<storage, read_write> tileMeta: array<vec2u>;

var<workgroup> claimed: atomic<u32>;
var<workgroup> farBits: atomic<u32>;

fn segmentDistance(p: vec2f, a: vec2f, b: vec2f) -> f32 {
  let ab = b - a;
  let l2 = dot(ab, ab);
  let t = select(0.0, clamp(dot(p - a, ab) / max(l2, 1e-12), 0.0, 1.0), l2 > 0.0);
  return length(p - (a + ab * t));
}

@compute @workgroup_size(LANES, 1, 1)
fn main(
  @builtin(workgroup_id) wg: vec3u,
  @builtin(local_invocation_index) lane: u32,
) {
  if (lane == 0u) {
    atomicStore(&claimed, 0u);
    atomicStore(&farBits, 0x7f7fffffu); // largest finite f32
  }
  workgroupBarrier();
  let tile = wg.xy;
  let tileIndex = tile.y * u.tiles.x + tile.x;
  let center = (vec2f(tile) + 0.5) * f32(TILE);
  let halfDiag = f32(TILE) * 0.5 * sqrt(2.0);
  for (var i = lane; i < u.segmentCount; i += LANES) {
    let s = segments[i];
    let d = segmentDistance(center, s.a, s.b) - materials[s.shape].emission.w;
    // Non-negative floats order as their bits do, so atomicMin works.
    atomicMin(&farBits, bitcast<u32>(max(d, 0.0)));
    if (d - halfDiag <= u.binRadius) {
      let slot = atomicAdd(&claimed, 1u);
      if (slot < BIN_CAPACITY) {
        bins[tileIndex * BIN_CAPACITY + slot] = i;
      }
    }
  }
  workgroupBarrier();
  if (lane == 0u) {
    tileMeta[tileIndex] = vec2u(atomicLoad(&claimed), atomicLoad(&farBits));
  }
}
`;

/** compute_scene_raster.wgsl, includes expanded. */
export const COMPUTE_SCENE_RASTER_WGSL =
  `// Compute scene rasterizer, pass 2: one workgroup per tile, one lane per
// pixel. The tile's binned segments are staged once in workgroup memory and
// every pixel tests only those; a tile whose bin overflowed falls back to all
// segments, so the result is always exact where it matters. Far from every
// binned segment the distance written is a lower bound (see pass 1), which
// sphere tracing accepts. Outputs match the fragment rasterizer: emission
// (a = coverage), transmittance (a = coverage), albedo, signed distance.

override TILE: u32 = 16u;
override BIN_CAPACITY: u32 = 128u;

struct SceneUniforms {
  size: vec2f,
  segmentCount: u32,
  shapeCount: u32,
  tiles: vec2u,
  binRadius: f32,
  pad: f32,
};
struct Segment {
  a: vec2f,
  b: vec2f,
  shape: u32,
  pad: u32,
};
struct Material {
  emission: vec4f,
  transmittance: vec4f,
  albedo: vec4f,
};
@group(0) @binding(0) var<uniform> u: SceneUniforms;
@group(0) @binding(1) var<storage, read> segments: array<Segment>;
@group(0) @binding(2) var<storage, read> materials: array<Material>;
@group(0) @binding(3) var<storage, read> bins: array<u32>;
@group(0) @binding(4) var<storage, read> tileMeta: array<vec2u>;
@group(0) @binding(5) var emissionOut: texture_storage_2d<rgba16float, write>;
@group(0) @binding(6) var transmittanceOut: texture_storage_2d<rgba16float, write>;
@group(0) @binding(7) var albedoOut: texture_storage_2d<rgba16float, write>;
@group(0) @binding(8) var distanceOut: texture_storage_2d<r32float, write>;

struct Staged {
  a: vec2f,
  b: vec2f,
  halfWidth: f32,
  shape: u32,
};
var<workgroup> staged: array<Staged, BIN_CAPACITY>;

fn segmentDistance(p: vec2f, a: vec2f, b: vec2f) -> f32 {
  let ab = b - a;
  let l2 = dot(ab, ab);
  let t = select(0.0, clamp(dot(p - a, ab) / max(l2, 1e-12), 0.0, 1.0), l2 > 0.0);
  return length(p - (a + ab * t));
}

@compute @workgroup_size(TILE, TILE, 1)
fn main(
  @builtin(workgroup_id) wg: vec3u,
  @builtin(global_invocation_id) gid: vec3u,
  @builtin(local_invocation_index) li: u32,
) {
  let tileIndex = wg.y * u.tiles.x + wg.x;
  let info = tileMeta[tileIndex];
  let binned = info.x;
  let complete = binned <= BIN_CAPACITY;
  if (complete) {
    for (var i = li; i < binned; i += TILE * TILE) {
      let s = segments[bins[tileIndex * BIN_CAPACITY + i]];
      staged[i] = Staged(s.a, s.b, materials[s.shape].emission.w, s.shape);
    }
  }
  workgroupBarrier();
  if (any(gid.xy >= vec2u(u.size))) {
    return;
  }
  let p = vec2f(gid.xy) + 0.5;
  var best = 1e4;
  var bestShape = 0u;
  if (complete) {
    for (var i = 0u; i < binned; i++) {
      let s = staged[i];
      let d = segmentDistance(p, s.a, s.b) - s.halfWidth;
      if (d < best) {
        best = d;
        bestShape = s.shape;
      }
    }
    if (best > u.binRadius) {
      // Every unbinned segment is farther than binRadius from every pixel of
      // this tile, and the distance field is 1-Lipschitz, so the tile-centre
      // distance minus this pixel's distance to the centre bounds the rest.
      let center = (vec2f(wg.xy) + 0.5) * f32(TILE);
      best = max(u.binRadius, bitcast<f32>(info.y) - length(p - center));
    }
  } else {
    for (var i = 0u; i < u.segmentCount; i++) {
      let s = segments[i];
      let d = segmentDistance(p, s.a, s.b) - materials[s.shape].emission.w;
      if (d < best) {
        best = d;
        bestShape = s.shape;
      }
    }
  }
  let texel = vec2i(gid.xy);
  if (u.segmentCount > 0u && best <= 0.0) {
    let m = materials[bestShape];
    textureStore(emissionOut, texel, vec4f(m.emission.rgb, 1.0));
    textureStore(transmittanceOut, texel, vec4f(m.transmittance.rgb, 1.0));
    textureStore(albedoOut, texel, vec4f(m.albedo.rgb, 1.0));
  } else {
    textureStore(emissionOut, texel, vec4f(0.0, 0.0, 0.0, 0.0));
    textureStore(transmittanceOut, texel, vec4f(1.0, 1.0, 1.0, 0.0));
    textureStore(albedoOut, texel, vec4f(0.0, 0.0, 0.0, 0.0));
  }
  textureStore(distanceOut, texel, vec4f(best, 0.0, 0.0, 1.0));
}
`;

/** compute_upsample.wgsl, includes expanded. */
export const COMPUTE_UPSAMPLE_WGSL =
  `// Per-pixel irradiance from per-probe irradiance when cascade 0's probe
// spacing is above one pixel: the bilinear gather of gather.wgsl, which
// commutes with the direction mean the cascade-0 pass already took.

override TILE: u32 = 16u;

struct UpsampleUniforms {
  probeCount: vec2u,
  probeSpacing: f32,
  pad: f32,
};
@group(0) @binding(0) var<uniform> u: UpsampleUniforms;
@group(0) @binding(1) var probeIrradiance: texture_2d<f32>;
@group(0) @binding(2) var irradianceOut: texture_storage_2d<rgba16float, write>;

@compute @workgroup_size(TILE, TILE, 1)
fn main(@builtin(global_invocation_id) gid: vec3u) {
  let dims = vec2i(textureDimensions(irradianceOut));
  if (any(vec2i(gid.xy) >= dims)) {
    return;
  }
  let pos = vec2f(gid.xy) + 0.5;
  let upos = pos / u.probeSpacing - 0.5;
  let base = vec2i(floor(upos));
  let f = fract(upos);
  let weights = vec4f((1.0 - f.x) * (1.0 - f.y), f.x * (1.0 - f.y), (1.0 - f.x) * f.y, f.x * f.y);
  var sum = vec3f(0.0);
  for (var c = 0; c < 4; c++) {
    let q = clamp(base + vec2i(c % 2, c / 2), vec2i(0), vec2i(u.probeCount) - vec2i(1));
    sum += weights[c] * textureLoad(probeIrradiance, q, 0).rgb;
  }
  textureStore(irradianceOut, vec2i(gid.xy), vec4f(sum, 1.0));
}
`;

/** display.wgsl, includes expanded. */
export const DISPLAY_WGSL =
  `// Fit a texture into the output and encode it for the canvas. Modes:
// 0 tone-mapped HDR radiance, 1 plain 0..1 color, 2 signed-distance ramp.
// Tone maps: 0 ACES (the sRGB fit from BakingLab), 1 the soft 1 - 1/(1+x)^2.5.

// ---- fullscreen_vertex.wgsl ----
@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}


struct DisplayUniforms {
  outputSize: vec2f,
  exposure: f32,
  mode: f32,
  tonemap: f32,
  pad0: f32,
  pad1: f32,
  pad2: f32,
};
@group(0) @binding(0) var<uniform> u: DisplayUniforms;
@group(0) @binding(1) var sourceTex: texture_2d<f32>;

fn encodeSrgb(linear: vec3f) -> vec3f {
  let c = clamp(linear, vec3f(0.0), vec3f(1.0));
  let low = 12.92 * c;
  let high = 1.055 * pow(c, vec3f(1.0 / 2.4)) - 0.055;
  return select(low, high, c > vec3f(0.0031308));
}

fn tonemapAces(color: vec3f) -> vec3f {
  // sRGB => AP1 => RRT/ODT fit => sRGB (column-major constructors).
  let inputMat = mat3x3f(
    vec3f(0.59719, 0.07600, 0.02840),
    vec3f(0.35458, 0.90834, 0.13383),
    vec3f(0.04823, 0.01566, 0.83777),
  );
  let outputMat = mat3x3f(
    vec3f(1.60475, -0.10208, -0.00327),
    vec3f(-0.53108, 1.10813, -0.07276),
    vec3f(-0.07367, -0.00605, 1.07602),
  );
  let c = inputMat * color;
  let a = c * (c + 0.0245786) - 0.000090537;
  let b = c * (0.983729 * c + 0.4329510) + 0.238081;
  return clamp(outputMat * (a / b), vec3f(0.0), vec3f(1.0));
}

fn tonemapSoft(color: vec3f) -> vec3f {
  return vec3f(1.0) - vec3f(1.0) / pow(vec3f(1.0) + color, vec3f(2.5));
}

@fragment
fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4f {
  // Texel loads rather than a sampler: the distance texture is r32float,
  // which is not filterable, and nearest scaling is fine for a monitor.
  let dims = vec2f(textureDimensions(sourceTex));
  let texel = vec2i(clamp(floor(pos.xy / u.outputSize * dims), vec2f(0.0), dims - vec2f(1.0)));
  let c = textureLoad(sourceTex, texel, 0);
  let mode = i32(u.mode);
  if (mode == 2) {
    let d = c.r;
    if (d <= 0.0) {
      return vec4f(1.0, 0.35, 0.2, 1.0);
    }
    let ring = 0.35 + 0.65 * fract(d / 16.0);
    return vec4f(vec3f(ring) * vec3f(0.6, 0.8, 1.0), 1.0);
  }
  if (mode == 1) {
    return vec4f(encodeSrgb(c.rgb), 1.0);
  }
  let exposed = max(c.rgb, vec3f(0.0)) * u.exposure;
  let mapped = select(tonemapAces(exposed), tonemapSoft(exposed), u.tonemap > 0.5);
  return vec4f(encodeSrgb(mapped), 1.0);
}
`;

/** fullscreen_vertex.wgsl, includes expanded. */
export const FULLSCREEN_VERTEX_WGSL = `@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}
`;

/** gather.wgsl, includes expanded. */
export const GATHER_WGSL = `// ---- fullscreen_vertex.wgsl ----
@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}


struct GatherUniforms {
  probeCount: vec2f,
  probeSpacing: f32,
  storedDirs: f32,
  tileCols: f32,
  pad0: f32,
  pad1: f32,
  pad2: f32,
};
@group(0) @binding(0) var<uniform> u: GatherUniforms;
@group(0) @binding(1) var radianceTex: texture_2d<f32>;

fn texelOf(probe: vec2i, stored: i32) -> vec2i {
  let cols = i32(u.tileCols);
  return vec2i(stored % cols, stored / cols) * vec2i(u.probeCount) + probe;
}

@fragment
fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4f {
  let upos = pos.xy / u.probeSpacing - 0.5;
  let base = vec2i(floor(upos));
  let f = fract(upos);
  let weights = vec4f((1.0 - f.x) * (1.0 - f.y), f.x * (1.0 - f.y), (1.0 - f.x) * f.y, f.x * f.y);
  let dirs = i32(u.storedDirs);
  var sum = vec3f(0.0);
  for (var c = 0; c < 4; c++) {
    let q = clamp(base + vec2i(c % 2, c / 2), vec2i(0), vec2i(u.probeCount) - vec2i(1));
    for (var k = 0; k < dirs; k++) {
      sum += weights[c] * textureLoad(radianceTex, texelOf(q, k), 0).rgb;
    }
  }
  return vec4f(sum / f32(dirs), 1.0);
}
`;

/** reference.wgsl, includes expanded. */
export const REFERENCE_WGSL = `// ---- fullscreen_vertex.wgsl ----
@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}


struct ReferenceUniforms {
  sky: vec4f,
  sceneSize: vec2f,
  rays: f32,
  maxDistance: f32,
  useDistanceField: f32,
  stepSize: f32,
  maxSteps: f32,
  pad: f32,
};
@group(0) @binding(0) var<uniform> u: ReferenceUniforms;
@group(0) @binding(1) var emissionTex: texture_2d<f32>;
@group(0) @binding(2) var transmittanceTex: texture_2d<f32>;
@group(0) @binding(3) var distanceTex: texture_2d<f32>;

// ---- march.wgsl ----
// Shared ray march. The including shader supplies the scene accessors
//   fn sceneDistance(texel: vec2i) -> f32      signed distance to the nearest outline
//   fn sceneMedium(texel: vec2i) -> Medium     emission and transmittance
// (the fragment programs read the scene textures directly; the compute
// cascade reads a workgroup-memory patch when the ray stays inside it) and
// \`marchParams()\`. Sphere-traces the distance field between outlines and
// integrates emission/transmittance per pixel of travel inside them. The
// emission of a step is E * (1 - tau^ds) / (1 - tau): the full E at an opaque
// hit whatever the step, E * ds through clear media.

struct MarchParams {
  sceneSize: vec2f,
  useDistanceField: bool,
  stepSize: f32,
  maxSteps: i32,
};
struct Hit {
  L: vec3f,
  T: vec3f,
};
struct Medium {
  E: vec3f,
  tau: vec3f,
};

fn inBounds(p: vec2f, size: vec2f) -> bool {
  return all(p >= vec2f(0.0)) && all(p < size);
}

// \`originDistance\` is the distance field at \`origin\` when the caller has it
// (every ray of a probe starts at the same point), or a negative number.
fn march(origin: vec2f, to: vec2f, mp: MarchParams, originDistance: f32) -> Hit {
  var L = vec3f(0.0);
  var T = vec3f(1.0);
  let delta = to - origin;
  let len = length(delta);
  if (len <= 0.0) {
    return Hit(L, T);
  }
  let dir = delta / len;
  var t = 0.0;
  // The first step's distance is known when the caller loaded it.
  if (mp.useDistanceField && originDistance > 0.5 && inBounds(origin, mp.sceneSize)) {
    t = originDistance;
  }
  for (var i = 0; i < mp.maxSteps; i++) {
    if (t >= len) { break; }
    let p = origin + dir * t;
    if (!inBounds(p, mp.sceneSize)) { break; }
    let texel = vec2i(floor(p));
    if (mp.useDistanceField) {
      let d = sceneDistance(texel);
      if (d > 0.5) {
        t += max(d, 0.5);
        continue;
      }
    }
    let ds = min(mp.stepSize, len - t);
    let m = sceneMedium(texel);
    let tau = clamp(m.tau, vec3f(0.0), vec3f(1.0));
    if (ds == 1.0) {
      // A whole pixel: tau^1 is tau and the emission factor is exactly 1,
      // for clear and absorbing media alike.
      L += T * m.E;
      T *= tau;
    } else {
      let tauDs = pow(tau, vec3f(ds));
      let clear = tau > vec3f(0.999);
      let emitFactor = select((vec3f(1.0) - tauDs) / max(vec3f(1.0) - tau, vec3f(1e-4)), vec3f(ds), clear);
      L += T * m.E * emitFactor;
      T *= tauDs;
    }
    if (max(T.r, max(T.g, T.b)) < 0.002) {
      T = vec3f(0.0);
      break;
    }
    t += ds;
  }
  return Hit(L, T);
}


fn sceneDistance(texel: vec2i) -> f32 {
  return textureLoad(distanceTex, texel, 0).r;
}

fn sceneMedium(texel: vec2i) -> Medium {
  return Medium(
    textureLoad(emissionTex, texel, 0).rgb,
    textureLoad(transmittanceTex, texel, 0).rgb,
  );
}

const TAU_F: f32 = 6.283185307179586;

@fragment
fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4f {
  let mp = MarchParams(u.sceneSize, u.useDistanceField > 0.5, u.stepSize, i32(u.maxSteps));
  let rays = i32(u.rays);
  var sum = vec3f(0.0);
  for (var k = 0; k < rays; k++) {
    let a = TAU_F * (f32(k) + 0.5) / u.rays;
    let w = vec2f(cos(a), sin(a));
    let hit = march(pos.xy, pos.xy + w * u.maxDistance, mp, -1.0);
    sum += hit.L + hit.T * u.sky.rgb;
  }
  return vec4f(sum / u.rays, 1.0);
}
`;

/** stroke_scene.wgsl, includes expanded. */
export const STROKE_SCENE_WGSL =
  `// WGSL for the stroke rasterizer, the cascade passes, the final gather, the
// bounce feed, the brute-force reference, and the display pass. Every pass is
// a fullscreen triangle; fragment positions are pixel centers of the pass's
// own output, and scene textures are addressed in render pixels.
// export const FULLSCREEN_VERTEX = /* wgsl */ \`
// @vertex
// fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
// var positions = array<vec2f, 3>(
// vec2f(-1.0, -1.0),
// vec2f(3.0, -1.0),
// vec2f(-1.0, 3.0),
// );
// return vec4f(positions[index], 0.0, 1.0);
// }
// \`;
// Nearest outline wins per pixel. Outputs: emission (a = coverage),
// transmittance (a = coverage), albedo, and the signed distance to the nearest
// outline edge in pixels (negative inside).

// ---- fullscreen_vertex.wgsl ----
@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}


struct SceneUniforms {
  size: vec2f,
  segmentCount: u32,
  shapeCount: u32,
};
struct Segment {
  a: vec2f,
  b: vec2f,
  shape: u32,
  pad: u32,
};
struct Material {
  emission: vec4f,       // rgb, halfWidth
  transmittance: vec4f,  // rgb, 0
  albedo: vec4f,         // rgb, 0
};
@group(0) @binding(0) var<uniform> u: SceneUniforms;
@group(0) @binding(1) var<storage, read> segments: array<Segment>;
@group(0) @binding(2) var<storage, read> materials: array<Material>;

struct Out {
  @location(0) emission: vec4f,
  @location(1) transmittance: vec4f,
  @location(2) albedo: vec4f,
  @location(3) distance: vec4f,
};

fn segmentDistance(p: vec2f, a: vec2f, b: vec2f) -> f32 {
  let ab = b - a;
  let l2 = dot(ab, ab);
  let t = select(0.0, clamp(dot(p - a, ab) / max(l2, 1e-12), 0.0, 1.0), l2 > 0.0);
  return length(p - (a + ab * t));
}

@fragment
fn fs(@builtin(position) pos: vec4f) -> Out {
  let p = pos.xy;
  var best = 1e4;
  var bestShape = 0u;
  for (var i = 0u; i < u.segmentCount; i++) {
    let s = segments[i];
    let d = segmentDistance(p, s.a, s.b) - materials[s.shape].emission.w;
    if (d < best) {
      best = d;
      bestShape = s.shape;
    }
  }
  var out: Out;
  if (u.segmentCount > 0u && best <= 0.0) {
    let m = materials[bestShape];
    out.emission = vec4f(m.emission.rgb, 1.0);
    out.transmittance = vec4f(m.transmittance.rgb, 1.0);
    out.albedo = vec4f(m.albedo.rgb, 1.0);
  } else {
    out.emission = vec4f(0.0, 0.0, 0.0, 0.0);
    out.transmittance = vec4f(1.0, 1.0, 1.0, 0.0);
    out.albedo = vec4f(0.0, 0.0, 0.0, 0.0);
  }
  out.distance = vec4f(best, 0.0, 0.0, 1.0);
  return out;
}
`;
