// Generated by tools/gen_shaders.ts from lib/radiance-cascades/shaders/*.wgsl.
// DO NOT EDIT; edit the .wgsl files and regenerate.

/** bounce.wgsl, includes expanded. */
export const BOUNCE_WGSL =
  `// Effective emission for the next frame: the scene's emission plus, inside an
// outline, the light that reached the outline last frame times its albedo.
// Incoming light is the hemispherical irradiance just outside the surface
// (cascade 0's stored directions, cosine-weighted against the outline
// normal), and a diffuse 2D surface re-emits albedo * E / 2.

// ---- fullscreen_vertex.wgsl ----
@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}


struct BounceUniforms {
  probeCount: vec2f,
  probeSpacing: f32,
  storedDirs: f32,
  tileCols: f32,
  rayCount: f32,
  strength: f32,
  offset: f32,
};
@group(0) @binding(0) var<uniform> u: BounceUniforms;
@group(0) @binding(1) var emissionTex: texture_2d<f32>;
@group(0) @binding(2) var albedoTex: texture_2d<f32>;
@group(0) @binding(3) var distanceTex: texture_2d<f32>;
@group(0) @binding(4) var radianceTex: texture_2d<f32>;

const TAU_F: f32 = 6.283185307179586;

fn texelOf(probe: vec2i, stored: i32) -> vec2i {
  let cols = i32(u.tileCols);
  return vec2i(stored % cols, stored / cols) * vec2i(u.probeCount) + probe;
}

@fragment
fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4f {
  let texel = vec2i(floor(pos.xy));
  let e = textureLoad(emissionTex, texel, 0);
  if (u.strength <= 0.0 || e.a < 0.5) {
    return e;
  }
  let dims = vec2i(textureDimensions(distanceTex));
  let d = textureLoad(distanceTex, texel, 0).r;
  let dx = textureLoad(distanceTex, clamp(texel + vec2i(1, 0), vec2i(0), dims - 1), 0).r
    - textureLoad(distanceTex, clamp(texel - vec2i(1, 0), vec2i(0), dims - 1), 0).r;
  let dy = textureLoad(distanceTex, clamp(texel + vec2i(0, 1), vec2i(0), dims - 1), 0).r
    - textureLoad(distanceTex, clamp(texel - vec2i(0, 1), vec2i(0), dims - 1), 0).r;
  var n = vec2f(dx, dy);
  let nl = length(n);
  let hasNormal = nl > 1e-4;
  n = select(vec2f(0.0), n / max(nl, 1e-4), hasNormal);
  let samplePos = pos.xy + n * (max(-d, 0.0) + u.offset);

  let upos = samplePos / u.probeSpacing - 0.5;
  let base = vec2i(floor(upos));
  let f = fract(upos);
  let weights = vec4f((1.0 - f.x) * (1.0 - f.y), f.x * (1.0 - f.y), (1.0 - f.x) * f.y, f.x * f.y);
  let dirs = i32(u.storedDirs);
  let group = u.rayCount / u.storedDirs;
  var irradiance = vec3f(0.0);
  for (var k = 0; k < dirs; k++) {
    var weight = 2.0 / f32(dirs);
    if (dirs > 1 && hasNormal) {
      let a = TAU_F * (f32(k) * group + group * 0.5) / u.rayCount;
      weight = max(0.0, dot(vec2f(cos(a), sin(a)), n)) * TAU_F / f32(dirs);
    }
    var L = vec3f(0.0);
    for (var c = 0; c < 4; c++) {
      let q = clamp(base + vec2i(c % 2, c / 2), vec2i(0), vec2i(u.probeCount) - vec2i(1));
      L += weights[c] * textureLoad(radianceTex, texelOf(q, k), 0).rgb;
    }
    irradiance += L * weight;
  }
  let albedo = textureLoad(albedoTex, texel, 0).rgb;
  return vec4f(e.rgb + u.strength * albedo * irradiance * 0.5, e.a);
}
`;

/** cascade.wgsl, includes expanded. */
export const CASCADE_WGSL =
  `// One cascade level. Direction-major layout: the texture is a grid of
// tiles, tile k holding the whole probe grid for stored direction k.
// Outputs: merged radiance, merged transmittance, and this level's own
// interval radiance before merging (for debugging).

// ---- fullscreen_vertex.wgsl ----
@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}


struct CascadeUniforms {
  sky: vec4f,
  sceneSize: vec2f,
  probeCount: vec2f,
  upperProbeCount: vec2f,
  probeSpacing: f32,
  upperSpacing: f32,
  rayCount: f32,
  storedDirs: f32,
  upperRayCount: f32,
  upperStoredDirs: f32,
  tileCols: f32,
  upperTileCols: f32,
  intervalStart: f32,
  intervalEnd: f32,
  branching: f32,
  isTop: f32,
  mergeMode: f32,
  preAverage: f32,
  useDistanceField: f32,
  stepSize: f32,
  intervalOverlap: f32,
  maxSteps: f32,
};
@group(0) @binding(0) var<uniform> u: CascadeUniforms;
@group(0) @binding(1) var emissionTex: texture_2d<f32>;
@group(0) @binding(2) var transmittanceTex: texture_2d<f32>;
@group(0) @binding(3) var distanceTex: texture_2d<f32>;
@group(0) @binding(4) var upperRadiance: texture_2d<f32>;
@group(0) @binding(5) var upperTransmittance: texture_2d<f32>;

// ---- march.wgsl ----
// Shared ray march. Bindings 1..3 must be the scene emission, transmittance
// and distance textures; the including shader supplies \\\`marchParams()\\\`.
// Sphere-traces the distance field between outlines and integrates
// emission/transmittance per pixel of travel inside them. The emission of a
// step is E * (1 - tau^ds) / (1 - tau): the full E at an opaque hit whatever
// the step, E * ds through clear media.

struct MarchParams {
  sceneSize: vec2f,
  useDistanceField: bool,
  stepSize: f32,
  maxSteps: i32,
};
struct Hit {
  L: vec3f,
  T: vec3f,
};

fn inBounds(p: vec2f, size: vec2f) -> bool {
  return all(p >= vec2f(0.0)) && all(p < size);
}

fn march(origin: vec2f, to: vec2f, mp: MarchParams) -> Hit {
  var L = vec3f(0.0);
  var T = vec3f(1.0);
  let delta = to - origin;
  let len = length(delta);
  if (len <= 0.0) {
    return Hit(L, T);
  }
  let dir = delta / len;
  var t = 0.0;
  for (var i = 0; i < mp.maxSteps; i++) {
    if (t >= len) { break; }
    let p = origin + dir * t;
    if (!inBounds(p, mp.sceneSize)) { break; }
    let texel = vec2i(floor(p));
    if (mp.useDistanceField) {
      let d = textureLoad(distanceTex, texel, 0).r;
      if (d > 0.5) {
        t += max(d, 0.5);
        continue;
      }
    }
    let ds = min(mp.stepSize, len - t);
    let tau = clamp(textureLoad(transmittanceTex, texel, 0).rgb, vec3f(0.0), vec3f(1.0));
    let E = textureLoad(emissionTex, texel, 0).rgb;
    let tauDs = pow(tau, vec3f(ds));
    let clear = tau > vec3f(0.999);
    let emitFactor = select((vec3f(1.0) - tauDs) / max(vec3f(1.0) - tau, vec3f(1e-4)), vec3f(ds), clear);
    L += T * E * emitFactor;
    T *= tauDs;
    if (max(T.r, max(T.g, T.b)) < 0.002) {
      T = vec3f(0.0);
      break;
    }
    t += ds;
  }
  return Hit(L, T);
}


fn marchParams() -> MarchParams {
  return MarchParams(u.sceneSize, u.useDistanceField > 0.5, u.stepSize, i32(u.maxSteps));
}

const TAU_F: f32 = 6.283185307179586;

fn dirOf(index: f32, count: f32) -> vec2f {
  let a = TAU_F * (index + 0.5) / count;
  return vec2f(cos(a), sin(a));
}

fn upperTexel(probe: vec2i, stored: i32) -> vec2i {
  let cols = i32(u.upperTileCols);
  let tile = vec2i(stored % cols, stored / cols);
  return tile * vec2i(u.upperProbeCount) + probe;
}

fn upperSample(probe: vec2i, stored: i32) -> Hit {
  let texel = upperTexel(probe, stored);
  return Hit(
    textureLoad(upperRadiance, texel, 0).rgb,
    textureLoad(upperTransmittance, texel, 0).rgb,
  );
}

fn upperProbe(base: vec2i, corner: i32) -> vec2i {
  return clamp(base + vec2i(corner % 2, corner / 2), vec2i(0), vec2i(u.upperProbeCount) - vec2i(1));
}

struct Merged {
  L: vec3f,
  T: vec3f,
  raw: vec3f,
};

// \`start\` is where this probe's interval begins for direction d: along d
// itself, or, when pre-averaging, along the stored (parent) direction so the
// level below's bilinear-fix rays end exactly where these begin (Yaazarai's
// fork).
fn castMerged(center: vec2f, d: i32, start: vec2f) -> Merged {
  let mp = marchParams();
  let w = dirOf(f32(d), u.rayCount);
  let t0 = u.intervalStart;
  let t1 = u.intervalEnd;
  let overlapEnd = center + w * (t0 + (t1 - t0) * u.intervalOverlap);
  if (u.isTop > 0.5) {
    let hit = march(start, overlapEnd, mp);
    return Merged(hit.L + hit.T * u.sky.rgb, hit.T, hit.L);
  }
  let upos = center / u.upperSpacing - 0.5;
  let base = vec2i(floor(upos));
  let f = fract(upos);
  let weights = vec4f((1.0 - f.x) * (1.0 - f.y), f.x * (1.0 - f.y), (1.0 - f.x) * f.y, f.x * f.y);
  let upperPerDir = u.upperStoredDirs >= u.upperRayCount - 0.5;
  let B = i32(u.branching);
  let childCount = select(1, B, upperPerDir);
  let mode = i32(u.mergeMode);

  if (mode == 1) {
    // Bilinear fix: one ray per upper probe, from this interval's start to
    // the point where that probe's child interval starts, merged with that
    // probe alone; the four merged results are then bilinearly weighted.
    var L = vec3f(0.0);
    var T = vec3f(0.0);
    var raw = vec3f(0.0);
    for (var c = 0; c < 4; c++) {
      let q = upperProbe(base, c);
      let qCenter = (vec2f(q) + 0.5) * u.upperSpacing;
      var Lc = vec3f(0.0);
      var Tc = vec3f(0.0);
      var rawc = vec3f(0.0);
      for (var k = 0; k < childCount; k++) {
        let stored = select(d, d * B + k, upperPerDir);
        let wc = select(w, dirOf(f32(d * B + k), u.upperRayCount), upperPerDir);
        let hit = march(start, qCenter + wc * t1, mp);
        let up = upperSample(q, stored);
        Lc += hit.L + hit.T * up.L;
        Tc += hit.T * up.T;
        rawc += hit.L;
      }
      let scale = weights[c] / f32(childCount);
      L += Lc * scale;
      T += Tc * scale;
      raw += rawc * scale;
    }
    return Merged(L, T, raw);
  }

  let hit = march(start, overlapEnd, mp);
  var upL = vec3f(0.0);
  var upT = vec3f(0.0);
  for (var c = 0; c < 4; c++) {
    let q = upperProbe(base, c);
    if (mode == 2) {
      // Parallax fix (Sannikov's MERGE_FIX 4): seen from the upper probe,
      // this ray's end point lies off the ray's own direction by a parallax
      // angle, so look the upper probe up in that direction, interpolating
      // its two nearest stored directions. When the upper level stores one
      // texel per ray, shift the whole child cone by the angle rather than
      // collapsing it to one direction, so the cone average survives when
      // cascade 0 has few, wide rays.
      let qCenter = (vec2f(q) + 0.5) * u.upperSpacing;
      let v = overlapEnd - qCenter;
      let nominal = TAU_F * (f32(d) + 0.5) / u.rayCount;
      var shift = atan2(v.y, v.x) - nominal;
      shift = shift - floor((shift + 3.14159265) / TAU_F) * TAU_F;
      let stored = u.upperStoredDirs;
      let shiftIndex = shift / TAU_F * stored;
      var Lc = vec3f(0.0);
      var Tc = vec3f(0.0);
      for (var k = 0; k < childCount; k++) {
        var idx = f32(select(d, d * B + k, upperPerDir)) + shiftIndex;
        idx = idx - floor(idx / stored) * stored;
        let i0 = i32(floor(idx)) % i32(stored);
        let i1 = (i0 + 1) % i32(stored);
        let fr = fract(idx);
        let s0 = upperSample(q, i0);
        let s1 = upperSample(q, i1);
        Lc += mix(s0.L, s1.L, fr);
        Tc += mix(s0.T, s1.T, fr);
      }
      upL += weights[c] * Lc / f32(childCount);
      upT += weights[c] * Tc / f32(childCount);
    } else {
      var Lc = vec3f(0.0);
      var Tc = vec3f(0.0);
      for (var k = 0; k < childCount; k++) {
        let s = upperSample(q, select(d, d * B + k, upperPerDir));
        Lc += s.L;
        Tc += s.T;
      }
      upL += weights[c] * Lc / f32(childCount);
      upT += weights[c] * Tc / f32(childCount);
    }
  }
  return Merged(hit.L + hit.T * upL, hit.T * upT, hit.L);
}

struct Out {
  @location(0) radiance: vec4f,
  @location(1) transmittance: vec4f,
  @location(2) raw: vec4f,
};

@fragment
fn fs(@builtin(position) pos: vec4f) -> Out {
  let texel = vec2i(floor(pos.xy));
  let probes = vec2i(u.probeCount);
  let tile = texel / probes;
  let probe = texel - tile * probes;
  let stored = tile.y * i32(u.tileCols) + tile.x;
  var out: Out;
  if (stored >= i32(u.storedDirs)) {
    out.radiance = vec4f(0.0);
    out.transmittance = vec4f(0.0);
    out.raw = vec4f(0.0);
    return out;
  }
  let center = (vec2f(probe) + 0.5) * u.probeSpacing;
  let group = select(1, i32(u.branching), u.preAverage > 0.5);
  let startDir = select(
    dirOf(f32(stored), u.rayCount),
    dirOf(f32(stored), u.storedDirs),
    u.preAverage > 0.5,
  );
  let start = center + startDir * u.intervalStart;
  var L = vec3f(0.0);
  var T = vec3f(0.0);
  var raw = vec3f(0.0);
  for (var j = 0; j < group; j++) {
    let m = castMerged(center, stored * group + j, start);
    L += m.L;
    T += m.T;
    raw += m.raw;
  }
  let inv = 1.0 / f32(group);
  out.radiance = vec4f(L * inv, 1.0);
  out.transmittance = vec4f(T * inv, 1.0);
  out.raw = vec4f(raw * inv, 1.0);
  return out;
}
`;

/** display.wgsl, includes expanded. */
export const DISPLAY_WGSL =
  `// Fit a texture into the output and encode it for the canvas. Modes:
// 0 tone-mapped HDR radiance, 1 plain 0..1 color, 2 signed-distance ramp.
// Tone maps: 0 ACES (the sRGB fit from BakingLab), 1 the soft 1 - 1/(1+x)^2.5.

// ---- fullscreen_vertex.wgsl ----
@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}


struct DisplayUniforms {
  outputSize: vec2f,
  exposure: f32,
  mode: f32,
  tonemap: f32,
  pad0: f32,
  pad1: f32,
  pad2: f32,
};
@group(0) @binding(0) var<uniform> u: DisplayUniforms;
@group(0) @binding(1) var sourceTex: texture_2d<f32>;

fn encodeSrgb(linear: vec3f) -> vec3f {
  let c = clamp(linear, vec3f(0.0), vec3f(1.0));
  let low = 12.92 * c;
  let high = 1.055 * pow(c, vec3f(1.0 / 2.4)) - 0.055;
  return select(low, high, c > vec3f(0.0031308));
}

fn tonemapAces(color: vec3f) -> vec3f {
  // sRGB => AP1 => RRT/ODT fit => sRGB (column-major constructors).
  let inputMat = mat3x3f(
    vec3f(0.59719, 0.07600, 0.02840),
    vec3f(0.35458, 0.90834, 0.13383),
    vec3f(0.04823, 0.01566, 0.83777),
  );
  let outputMat = mat3x3f(
    vec3f(1.60475, -0.10208, -0.00327),
    vec3f(-0.53108, 1.10813, -0.07276),
    vec3f(-0.07367, -0.00605, 1.07602),
  );
  let c = inputMat * color;
  let a = c * (c + 0.0245786) - 0.000090537;
  let b = c * (0.983729 * c + 0.4329510) + 0.238081;
  return clamp(outputMat * (a / b), vec3f(0.0), vec3f(1.0));
}

fn tonemapSoft(color: vec3f) -> vec3f {
  return vec3f(1.0) - vec3f(1.0) / pow(vec3f(1.0) + color, vec3f(2.5));
}

@fragment
fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4f {
  // Texel loads rather than a sampler: the distance texture is r32float,
  // which is not filterable, and nearest scaling is fine for a monitor.
  let dims = vec2f(textureDimensions(sourceTex));
  let texel = vec2i(clamp(floor(pos.xy / u.outputSize * dims), vec2f(0.0), dims - vec2f(1.0)));
  let c = textureLoad(sourceTex, texel, 0);
  let mode = i32(u.mode);
  if (mode == 2) {
    let d = c.r;
    if (d <= 0.0) {
      return vec4f(1.0, 0.35, 0.2, 1.0);
    }
    let ring = 0.35 + 0.65 * fract(d / 16.0);
    return vec4f(vec3f(ring) * vec3f(0.6, 0.8, 1.0), 1.0);
  }
  if (mode == 1) {
    return vec4f(encodeSrgb(c.rgb), 1.0);
  }
  let exposed = max(c.rgb, vec3f(0.0)) * u.exposure;
  let mapped = select(tonemapAces(exposed), tonemapSoft(exposed), u.tonemap > 0.5);
  return vec4f(encodeSrgb(mapped), 1.0);
}
`;

/** fullscreen_vertex.wgsl, includes expanded. */
export const FULLSCREEN_VERTEX_WGSL = `@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}
`;

/** gather.wgsl, includes expanded. */
export const GATHER_WGSL = `// ---- fullscreen_vertex.wgsl ----
@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}


struct GatherUniforms {
  probeCount: vec2f,
  probeSpacing: f32,
  storedDirs: f32,
  tileCols: f32,
  pad0: f32,
  pad1: f32,
  pad2: f32,
};
@group(0) @binding(0) var<uniform> u: GatherUniforms;
@group(0) @binding(1) var radianceTex: texture_2d<f32>;

fn texelOf(probe: vec2i, stored: i32) -> vec2i {
  let cols = i32(u.tileCols);
  return vec2i(stored % cols, stored / cols) * vec2i(u.probeCount) + probe;
}

@fragment
fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4f {
  let upos = pos.xy / u.probeSpacing - 0.5;
  let base = vec2i(floor(upos));
  let f = fract(upos);
  let weights = vec4f((1.0 - f.x) * (1.0 - f.y), f.x * (1.0 - f.y), (1.0 - f.x) * f.y, f.x * f.y);
  let dirs = i32(u.storedDirs);
  var sum = vec3f(0.0);
  for (var c = 0; c < 4; c++) {
    let q = clamp(base + vec2i(c % 2, c / 2), vec2i(0), vec2i(u.probeCount) - vec2i(1));
    for (var k = 0; k < dirs; k++) {
      sum += weights[c] * textureLoad(radianceTex, texelOf(q, k), 0).rgb;
    }
  }
  return vec4f(sum / f32(dirs), 1.0);
}
`;

/** reference.wgsl, includes expanded. */
export const REFERENCE_WGSL = `// ---- fullscreen_vertex.wgsl ----
@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}


struct ReferenceUniforms {
  sky: vec4f,
  sceneSize: vec2f,
  rays: f32,
  maxDistance: f32,
  useDistanceField: f32,
  stepSize: f32,
  maxSteps: f32,
  pad: f32,
};
@group(0) @binding(0) var<uniform> u: ReferenceUniforms;
@group(0) @binding(1) var emissionTex: texture_2d<f32>;
@group(0) @binding(2) var transmittanceTex: texture_2d<f32>;
@group(0) @binding(3) var distanceTex: texture_2d<f32>;

// ---- march.wgsl ----
// Shared ray march. Bindings 1..3 must be the scene emission, transmittance
// and distance textures; the including shader supplies \\\`marchParams()\\\`.
// Sphere-traces the distance field between outlines and integrates
// emission/transmittance per pixel of travel inside them. The emission of a
// step is E * (1 - tau^ds) / (1 - tau): the full E at an opaque hit whatever
// the step, E * ds through clear media.

struct MarchParams {
  sceneSize: vec2f,
  useDistanceField: bool,
  stepSize: f32,
  maxSteps: i32,
};
struct Hit {
  L: vec3f,
  T: vec3f,
};

fn inBounds(p: vec2f, size: vec2f) -> bool {
  return all(p >= vec2f(0.0)) && all(p < size);
}

fn march(origin: vec2f, to: vec2f, mp: MarchParams) -> Hit {
  var L = vec3f(0.0);
  var T = vec3f(1.0);
  let delta = to - origin;
  let len = length(delta);
  if (len <= 0.0) {
    return Hit(L, T);
  }
  let dir = delta / len;
  var t = 0.0;
  for (var i = 0; i < mp.maxSteps; i++) {
    if (t >= len) { break; }
    let p = origin + dir * t;
    if (!inBounds(p, mp.sceneSize)) { break; }
    let texel = vec2i(floor(p));
    if (mp.useDistanceField) {
      let d = textureLoad(distanceTex, texel, 0).r;
      if (d > 0.5) {
        t += max(d, 0.5);
        continue;
      }
    }
    let ds = min(mp.stepSize, len - t);
    let tau = clamp(textureLoad(transmittanceTex, texel, 0).rgb, vec3f(0.0), vec3f(1.0));
    let E = textureLoad(emissionTex, texel, 0).rgb;
    let tauDs = pow(tau, vec3f(ds));
    let clear = tau > vec3f(0.999);
    let emitFactor = select((vec3f(1.0) - tauDs) / max(vec3f(1.0) - tau, vec3f(1e-4)), vec3f(ds), clear);
    L += T * E * emitFactor;
    T *= tauDs;
    if (max(T.r, max(T.g, T.b)) < 0.002) {
      T = vec3f(0.0);
      break;
    }
    t += ds;
  }
  return Hit(L, T);
}


const TAU_F: f32 = 6.283185307179586;

@fragment
fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4f {
  let mp = MarchParams(u.sceneSize, u.useDistanceField > 0.5, u.stepSize, i32(u.maxSteps));
  let rays = i32(u.rays);
  var sum = vec3f(0.0);
  for (var k = 0; k < rays; k++) {
    let a = TAU_F * (f32(k) + 0.5) / u.rays;
    let w = vec2f(cos(a), sin(a));
    let hit = march(pos.xy, pos.xy + w * u.maxDistance, mp);
    sum += hit.L + hit.T * u.sky.rgb;
  }
  return vec4f(sum / u.rays, 1.0);
}
`;

/** stroke_scene.wgsl, includes expanded. */
export const STROKE_SCENE_WGSL =
  `// WGSL for the stroke rasterizer, the cascade passes, the final gather, the
// bounce feed, the brute-force reference, and the display pass. Every pass is
// a fullscreen triangle; fragment positions are pixel centers of the pass's
// own output, and scene textures are addressed in render pixels.
// export const FULLSCREEN_VERTEX = /* wgsl */ \`
// @vertex
// fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
// var positions = array<vec2f, 3>(
// vec2f(-1.0, -1.0),
// vec2f(3.0, -1.0),
// vec2f(-1.0, 3.0),
// );
// return vec4f(positions[index], 0.0, 1.0);
// }
// \`;
// Nearest outline wins per pixel. Outputs: emission (a = coverage),
// transmittance (a = coverage), albedo, and the signed distance to the nearest
// outline edge in pixels (negative inside).

// ---- fullscreen_vertex.wgsl ----
@vertex
fn vs(@builtin(vertex_index) index: u32) -> @builtin(position) vec4f {
  var positions = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f(3.0, -1.0),
    vec2f(-1.0, 3.0),
  );
  return vec4f(positions[index], 0.0, 1.0);
}


struct SceneUniforms {
  size: vec2f,
  segmentCount: u32,
  shapeCount: u32,
};
struct Segment {
  a: vec2f,
  b: vec2f,
  shape: u32,
  pad: u32,
};
struct Material {
  emission: vec4f,       // rgb, halfWidth
  transmittance: vec4f,  // rgb, 0
  albedo: vec4f,         // rgb, 0
};
@group(0) @binding(0) var<uniform> u: SceneUniforms;
@group(0) @binding(1) var<storage, read> segments: array<Segment>;
@group(0) @binding(2) var<storage, read> materials: array<Material>;

struct Out {
  @location(0) emission: vec4f,
  @location(1) transmittance: vec4f,
  @location(2) albedo: vec4f,
  @location(3) distance: vec4f,
};

fn segmentDistance(p: vec2f, a: vec2f, b: vec2f) -> f32 {
  let ab = b - a;
  let l2 = dot(ab, ab);
  let t = select(0.0, clamp(dot(p - a, ab) / max(l2, 1e-12), 0.0, 1.0), l2 > 0.0);
  return length(p - (a + ab * t));
}

@fragment
fn fs(@builtin(position) pos: vec4f) -> Out {
  let p = pos.xy;
  var best = 1e4;
  var bestShape = 0u;
  for (var i = 0u; i < u.segmentCount; i++) {
    let s = segments[i];
    let d = segmentDistance(p, s.a, s.b) - materials[s.shape].emission.w;
    if (d < best) {
      best = d;
      bestShape = s.shape;
    }
  }
  var out: Out;
  if (u.segmentCount > 0u && best <= 0.0) {
    let m = materials[bestShape];
    out.emission = vec4f(m.emission.rgb, 1.0);
    out.transmittance = vec4f(m.transmittance.rgb, 1.0);
    out.albedo = vec4f(m.albedo.rgb, 1.0);
  } else {
    out.emission = vec4f(0.0, 0.0, 0.0, 0.0);
    out.transmittance = vec4f(1.0, 1.0, 1.0, 0.0);
    out.albedo = vec4f(0.0, 0.0, 0.0, 0.0);
  }
  out.distance = vec4f(best, 0.0, 0.0, 1.0);
  return out;
}
`;
